import React from 'react';

const emptyExternal = { name: '', mobile: '', company: '', vehicleType: '', plateNumber: '', referenceNumber: '', notes: '' };

const DeliveryAssignmentFields = ({ assignmentType, onAssignmentTypeChange, riders, selectedRiderId, onRiderChange, thirdPartyRider = emptyExternal, onThirdPartyChange }) => (
  <div className="space-y-3">
    <div><p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">Assign Delivery To</p><div className="grid grid-cols-2 gap-2">{[['internal','Internal Rider'],['third_party','Third-Party Rider']].map(([value,label])=><button key={value} type="button" onClick={()=>onAssignmentTypeChange(value)} className={`h-10 rounded-xl border text-[10px] font-black uppercase ${assignmentType===value?'bg-slate-900 text-white border-slate-900':'bg-white text-slate-600 border-slate-200'}`}>{label}</button>)}</div></div>
    {assignmentType === 'internal' ? <select value={selectedRiderId} onChange={event=>onRiderChange(event.target.value)} className="w-full h-11 px-3 rounded-xl border border-slate-200 bg-white text-xs font-bold text-slate-700"><option value="">Select active rider</option>{riders.map(rider=><option key={rider._id} value={rider._id}>{rider.firstName} {rider.lastName} · {rider.riderProfile?.staffId} · {rider.activeDeliveryCount} active · {rider.riderProfile?.deliveryZone || rider.store?.name || 'Assigned branch'}</option>)}</select> : <div className="grid grid-cols-2 gap-2"><input required placeholder="Rider name *" value={thirdPartyRider.name} onChange={e=>onThirdPartyChange({...thirdPartyRider,name:e.target.value})} className="h-10 px-3 rounded-xl border text-xs"/><input required placeholder="Mobile number *" value={thirdPartyRider.mobile} onChange={e=>onThirdPartyChange({...thirdPartyRider,mobile:e.target.value})} className="h-10 px-3 rounded-xl border text-xs"/><input required placeholder="Courier company *" value={thirdPartyRider.company} onChange={e=>onThirdPartyChange({...thirdPartyRider,company:e.target.value})} className="h-10 px-3 rounded-xl border text-xs"/><select value={thirdPartyRider.vehicleType} onChange={e=>onThirdPartyChange({...thirdPartyRider,vehicleType:e.target.value})} className="h-10 px-3 rounded-xl border text-xs"><option value="">Vehicle type</option><option value="motorcycle">Motorcycle</option><option value="bicycle">Bicycle</option><option value="car">Car</option><option value="van">Van</option><option value="other">Other</option></select><input placeholder="Plate number" value={thirdPartyRider.plateNumber} onChange={e=>onThirdPartyChange({...thirdPartyRider,plateNumber:e.target.value})} className="h-10 px-3 rounded-xl border text-xs"/><input placeholder="External reference" value={thirdPartyRider.referenceNumber} onChange={e=>onThirdPartyChange({...thirdPartyRider,referenceNumber:e.target.value})} className="h-10 px-3 rounded-xl border text-xs"/><textarea placeholder="Assignment notes" value={thirdPartyRider.notes} onChange={e=>onThirdPartyChange({...thirdPartyRider,notes:e.target.value})} className="col-span-2 min-h-16 p-3 rounded-xl border text-xs resize-none"/></div>}
  </div>
);

export { emptyExternal };
export default DeliveryAssignmentFields;
