services:
  - type: web
    name: pawzzle
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: REACT_APP_RECAPTCHA_SITE_KEY
        sync: false
