// Location constants for dropdown lists
export const DEFAULT_COUNTRY = 'PH';

export const COUNTRIES = [
  { value: 'PH', label: 'Philippines' },
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'AU', label: 'Australia' },
  { value: 'JP', label: 'Japan' },
  { value: 'SG', label: 'Singapore' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'TH', label: 'Thailand' },
  { value: 'IN', label: 'India' },
  { value: 'CN', label: 'China' },
  { value: 'KR', label: 'South Korea' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'DE', label: 'Germany' },
  { value: 'FR', label: 'France' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'BE', label: 'Belgium' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'SE', label: 'Sweden' },
  { value: 'NO', label: 'Norway' },
  { value: 'DK', label: 'Denmark' },
  { value: 'FI', label: 'Finland' },
  { value: 'BR', label: 'Brazil' },
  { value: 'MX', label: 'Mexico' },
  { value: 'AR', label: 'Argentina' }
];

export const PHILIPPINE_PROVINCES = [
  { value: 'metro_manila', label: 'Metro Manila' },
  { value: 'abra', label: 'Abra' },
  { value: 'agusan_del_norte', label: 'Agusan del Norte' },
  { value: 'agusan_del_sur', label: 'Agusan del Sur' },
  { value: 'aklan', label: 'Aklan' },
  { value: 'albay', label: 'Albay' },
  { value: 'antique', label: 'Antique' },
  { value: 'apayao', label: 'Apayao' },
  { value: 'aurora', label: 'Aurora' },
  { value: 'bataan', label: 'Bataan' },
  { value: 'batanes', label: 'Batanes' },
  { value: 'batangas', label: 'Batangas' },
  { value: 'biliran', label: 'Biliran' },
  { value: 'bohol', label: 'Bohol' },
  { value: 'bukidnon', label: 'Bukidnon' },
  { value: 'bulacan', label: 'Bulacan' },
  { value: 'cagayan', label: 'Cagayan' },
  { value: 'camarines_norte', label: 'Camarines Norte' },
  { value: 'camarines_sur', label: 'Camarines Sur' },
  { value: 'camiguin', label: 'Camiguin' },
  { value: 'capiz', label: 'Capiz' },
  { value: 'catanduanes', label: 'Catanduanes' },
  { value: 'cavite', label: 'Cavite' },
  { value: 'cebu', label: 'Cebu' },
  { value: 'compostela_valley', label: 'Compostela Valley' },
  { value: 'cotabato', label: 'Cotabato' },
  { value: 'davao_del_norte', label: 'Davao del Norte' },
  { value: 'davao_del_sur', label: 'Davao del Sur' },
  { value: 'davao_occidental', label: 'Davao Occidental' },
  { value: 'davao_oriental', label: 'Davao Oriental' },
  { value: 'dinagat_islands', label: 'Dinagat Islands' },
  { value: 'eastern_samar', label: 'Eastern Samar' },
  { value: 'guimaras', label: 'Guimaras' },
  { value: 'ifugao', label: 'Ifugao' },
  { value: 'ilocos_norte', label: 'Ilocos Norte' },
  { value: 'ilocos_sur', label: 'Ilocos Sur' },
  { value: 'isabela', label: 'Isabela' },
  { value: 'kalinga', label: 'Kalinga' },
  { value: 'la_union', label: 'La Union' },
  { value: 'laguna', label: 'Laguna' },
  { value: 'lanao_del_norte', label: 'Lanao del Norte' },
  { value: 'lanao_del_sur', label: 'Lanao del Sur' },
  { value: 'leyte', label: 'Leyte' },
  { value: 'maguindanao', label: 'Maguindanao' },
  { value: 'marinduque', label: 'Marinduque' },
  { value: 'masbate', label: 'Masbate' },
  { value: 'misamis_occidental', label: 'Misamis Occidental' },
  { value: 'misamis_oriental', label: 'Misamis Oriental' },
  { value: 'mountain_province', label: 'Mountain Province' },
  { value: 'negros_occidental', label: 'Negros Occidental' },
  { value: 'negros_oriental', label: 'Negros Oriental' },
  { value: 'northern_samar', label: 'Northern Samar' },
  { value: 'nueva_ecija', label: 'Nueva Ecija' },
  { value: 'nueva_vizcaya', label: 'Nueva Vizcaya' },
  { value: 'occidental_mindoro', label: 'Occidental Mindoro' },
  { value: 'oriental_mindoro', label: 'Oriental Mindoro' },
  { value: 'palawan', label: 'Palawan' },
  { value: 'pampanga', label: 'Pampanga' },
  { value: 'pangasinan', label: 'Pangasinan' },
  { value: 'quezon', label: 'Quezon' },
  { value: 'quirino', label: 'Quirino' },
  { value: 'rizal', label: 'Rizal' },
  { value: 'romblon', label: 'Romblon' },
  { value: 'samar', label: 'Samar' },
  { value: 'sarangani', label: 'Sarangani' },
  { value: 'siquijor', label: 'Siquijor' },
  { value: 'sorsogon', label: 'Sorsogon' },
  { value: 'south_cotabato', label: 'South Cotabato' },
  { value: 'southern_leyte', label: 'Southern Leyte' },
  { value: 'sultan_kudarat', label: 'Sultan Kudarat' },
  { value: 'sulu', label: 'Sulu' },
  { value: 'surigao_del_norte', label: 'Surigao del Norte' },
  { value: 'surigao_del_sur', label: 'Surigao del Sur' },
  { value: 'tarlac', label: 'Tarlac' },
  { value: 'tawi_tawi', label: 'Tawi-Tawi' },
  { value: 'zambales', label: 'Zambales' },
  { value: 'zamboanga_del_norte', label: 'Zamboanga del Norte' },
  { value: 'zamboanga_del_sur', label: 'Zamboanga del Sur' },
  { value: 'zamboanga_sibugay', label: 'Zamboanga Sibugay' }
];

export const MAJOR_CITIES = [
  { value: 'manila', label: 'Manila' },
  { value: 'quezon', label: 'Quezon City' },
  { value: 'caloocan', label: 'Caloocan City' },
  { value: 'davao', label: 'Davao City' },
  { value: 'cebu', label: 'Cebu City' },
  { value: 'bacolod', label: 'Bacolod City' },
  { value: 'iloilo', label: 'Iloilo City' },
  { value: 'cagayan_de_oro', label: "Cagayan de Oro" },
  { value: 'general_santos', label: 'General Santos City' },
  { value: 'pasig', label: 'Pasig City' },
  { value: 'makati', label: 'Makati City' },
  { value: 'mandaluyong', label: 'Mandaluyong City' },
  { value: 'san_juan', label: 'San Juan City' },
  { value: 'taguig', label: 'Taguig City' },
  { value: 'pasay', label: 'Pasay City' },
  { value: 'paranaque', label: 'Paranaque City' },
  { value: 'las_pinas', label: 'Las Pinas City' },
  { value: 'marikina', label: 'Marikina City' },
  { value: 'valenzuela', label: 'Valenzuela City' },
  { value: 'muntinlupa', label: 'Muntinlupa City' },
  { value: 'tagaytay', label: 'Tagaytay City' },
  { value: 'cavite', label: 'Cavite City' },
  { value: 'lipa', label: 'Lipa City' },
  { value: 'batangas', label: 'Batangas City' },
  { value: 'laguna', label: 'Laguna City' },
  { value: 'san_pablo', label: 'San Pablo City' },
  { value: 'san_pedro', label: 'San Pedro City' },
  { value: 'binan', label: 'Binan City' },
  { value: 'santa_rosa', label: 'Santa Rosa City' },
  { value: 'cabuyao', label: 'Cabuyao City' },
  { value: 'calamba', label: 'Calamba City' },
  { value: 'los_banos', label: 'Los Banos' },
  { value: 'bay', label: 'Bay' },
  { value: 'san_pablo', label: 'San Pablo City' }
];

// Sample barangays for Manila (you can expand this list)
export const MANILA_BARANGAYS = [
  { value: '001', label: 'Barangay 1' },
  { value: '002', label: 'Barangay 2' },
  { value: '003', label: 'Barangay 3' },
  { value: '004', label: 'Barangay 4' },
  { value: '005', label: 'Barangay 5' },
  { value: '006', label: 'Barangay 6' },
  { value: '007', label: 'Barangay 7' },
  { value: '008', label: 'Barangay 8' },
  { value: '009', label: 'Barangay 9' },
  { value: '010', label: 'Barangay 10' }
];

// Function to get cities based on province
export const getCitiesByProvince = (provinceCode) => {
  const citiesByProvince = {
    metro_manila: [
      { value: 'manila', label: 'Manila' },
      { value: 'quezon_city', label: 'Quezon City' },
      { value: 'caloocan', label: 'Caloocan' },
      { value: 'las_pinas', label: 'Las Piñas' },
      { value: 'makati', label: 'Makati' },
      { value: 'malabon', label: 'Malabon' },
      { value: 'mandaluyong', label: 'Mandaluyong' },
      { value: 'marikina', label: 'Marikina' },
      { value: 'muntinlupa', label: 'Muntinlupa' },
      { value: 'navotas', label: 'Navotas' },
      { value: 'paranaque', label: 'Parañaque' },
      { value: 'pasay', label: 'Pasay' },
      { value: 'pasig', label: 'Pasig' },
      { value: 'san_juan', label: 'San Juan' },
      { value: 'taguig', label: 'Taguig' },
      { value: 'valenzuela', label: 'Valenzuela' }
    ],
    cebu: [
      { value: 'cebu_city', label: 'Cebu City' },
      { value: 'lapu_lapu', label: 'Lapu-Lapu City' },
      { value: 'mandaluyong_cebu', label: 'Mandaue City' },
      { value: 'talisay', label: 'Talisay' },
      { value: 'toledo', label: 'Toledo City' }
    ],
    davao_del_sur: [
      { value: 'davao_city', label: 'Davao City' },
      { value: 'digos', label: 'Digos City' },
      { value: 'tagum', label: 'Tagum City' }
    ],
    cavite: [
      { value: 'cavite_city', label: 'Cavite City' },
      { value: 'bacoor', label: 'Bacoor' },
      { value: 'carmona', label: 'Carmona' },
      { value: 'dasmarinas', label: 'Dasmariñas' },
      { value: 'general_trias', label: 'General Trias' },
      { value: 'imus', label: 'Imus' },
      { value: 'kawit', label: 'Kawit' },
      { value: 'magallanes', label: 'Magallanes' },
      { value: 'maragondon', label: 'Maragondon' },
      { value: 'mendez', label: 'Mendez' },
      { value: 'naic', label: 'Naic' },
      { value: 'noveleta', label: 'Noveleta' },
      { value: 'rosario', label: 'Rosario' },
      { value: 'silang', label: 'Silang' },
      { value: 'tagaytay', label: 'Tagaytay' },
      { value: 'ternate', label: 'Ternate' },
      { value: 'alfonso', label: 'Alfonso' },
      { value: 'amadeo', label: 'Amadeo' },
      { value: 'general_emilio_aguinaldo', label: 'General Emilio Aguinaldo' },
      { value: 'general_mariano_alvarez', label: 'General Mariano Alvarez' },
      { value: 'indang', label: 'Indang' },
      { value: 'tanza', label: 'Tanza' },
      { value: 'trece_martires', label: 'Trece Martires' }
    ]
  };

  return citiesByProvince[provinceCode] || [];
};

// Function to get barangays based on city
export const getBarangaysByCity = (cityCode) => {
  const barangaysByCity = {
    manila: [
      { value: 'binondo', label: 'Binondo' },
      { value: 'ermita', label: 'Ermita' },
      { value: 'intramuros', label: 'Intramuros' },
      { value: 'malate', label: 'Malate' },
      { value: 'paco', label: 'Paco' },
      { value: 'pandacan', label: 'Pandacan' },
      { value: 'port_area', label: 'Port Area' },
      { value: 'quiapo', label: 'Quiapo' },
      { value: 'sampaloc', label: 'Sampaloc' },
      { value: 'san_miguel', label: 'San Miguel' },
      { value: 'san_nicolas', label: 'San Nicolas' },
      { value: 'santa_ana', label: 'Santa Ana' },
      { value: 'santa_cruz', label: 'Santa Cruz' },
      { value: 'tondo', label: 'Tondo' }
    ],
    quezon_city: [
      { value: 'commonwealth', label: 'Commonwealth' },
      { value: 'cubao', label: 'Cubao' },
      { value: 'diliman', label: 'Diliman' },
      { value: 'kamuning', label: 'Kamuning' },
      { value: 'libis', label: 'Libis' },
      { value: 'new_manila', label: 'New Manila' },
      { value: 'san_jose', label: 'San Jose' },
      { value: 'santa_mesa', label: 'Santa Mesa' }
    ],
    cebu_city: [
      { value: 'carbon', label: 'Carbon' },
      { value: 'guadalupe', label: 'Guadalupe' },
      { value: 'lahug', label: 'Lahug' },
      { value: 'mabolo', label: 'Mabolo' },
      { value: 'parian', label: 'Parian' },
      { value: 'tisa', label: 'Tisa' },
      { value: 'uptown', label: 'Uptown' }
    ],
    cavite_city: [
      { value: 'barangay_1', label: 'Barangay 1' },
      { value: 'barangay_2', label: 'Barangay 2' },
      { value: 'barangay_3', label: 'Barangay 3' },
      { value: 'barangay_4', label: 'Barangay 4' },
      { value: 'barangay_5', label: 'Barangay 5' },
      { value: 'barangay_6', label: 'Barangay 6' },
      { value: 'barangay_7', label: 'Barangay 7' },
      { value: 'barangay_8', label: 'Barangay 8' },
      { value: 'barangay_9', label: 'Barangay 9' },
      { value: 'barangay_10m', label: 'Barangay 10M' },
      { value: 'barangay_10a', label: 'Barangay 10A' },
      { value: 'barangay_10b', label: 'Barangay 10B' },
      { value: 'barangay_11', label: 'Barangay 11' },
      { value: 'barangay_12', label: 'Barangay 12' },
      { value: 'barangay_13', label: 'Barangay 13' },
      { value: 'barangay_14', label: 'Barangay 14' },
      { value: 'barangay_15', label: 'Barangay 15' },
      { value: 'barangay_16', label: 'Barangay 16' },
      { value: 'barangay_17', label: 'Barangay 17' },
      { value: 'barangay_18', label: 'Barangay 18' },
      { value: 'barangay_19', label: 'Barangay 19' },
      { value: 'barangay_20', label: 'Barangay 20' },
      { value: 'barangay_21', label: 'Barangay 21' },
      { value: 'barangay_22m', label: 'Barangay 22M' },
      { value: 'barangay_22a', label: 'Barangay 22A' },
      { value: 'barangay_23', label: 'Barangay 23' },
      { value: 'barangay_24', label: 'Barangay 24' },
      { value: 'barangay_25', label: 'Barangay 25' },
      { value: 'barangay_26', label: 'Barangay 26' },
      { value: 'barangay_27', label: 'Barangay 27' },
      { value: 'barangay_28', label: 'Barangay 28' },
      { value: 'barangay_29m', label: 'Barangay 29M' },
      { value: 'barangay_29a', label: 'Barangay 29A' },
      { value: 'barangay_30', label: 'Barangay 30' },
      { value: 'barangay_31', label: 'Barangay 31' },
      { value: 'barangay_32', label: 'Barangay 32' },
      { value: 'barangay_33', label: 'Barangay 33' },
      { value: 'barangay_34', label: 'Barangay 34' },
      { value: 'barangay_35', label: 'Barangay 35' },
      { value: 'barangay_36m', label: 'Barangay 36M' },
      { value: 'barangay_36a', label: 'Barangay 36A' },
      { value: 'barangay_37m', label: 'Barangay 37M' },
      { value: 'barangay_37a', label: 'Barangay 37A' },
      { value: 'barangay_38m', label: 'Barangay 38M' },
      { value: 'barangay_38a', label: 'Barangay 38A' },
      { value: 'barangay_39', label: 'Barangay 39' },
      { value: 'barangay_40', label: 'Barangay 40' },
      { value: 'barangay_41', label: 'Barangay 41' },
      { value: 'barangay_42m', label: 'Barangay 42M' },
      { value: 'barangay_42a', label: 'Barangay 42A' },
      { value: 'barangay_42b', label: 'Barangay 42B' },
      { value: 'barangay_42c', label: 'Barangay 42C' },
      { value: 'barangay_43', label: 'Barangay 43' },
      { value: 'barangay_44', label: 'Barangay 44' },
      { value: 'barangay_45m', label: 'Barangay 45M' },
      { value: 'barangay_45a', label: 'Barangay 45A' },
      { value: 'barangay_46', label: 'Barangay 46' },
      { value: 'barangay_47m', label: 'Barangay 47M' },
      { value: 'barangay_47a', label: 'Barangay 47A' },
      { value: 'barangay_47b', label: 'Barangay 47B' },
      { value: 'barangay_48m', label: 'Barangay 48M' },
      { value: 'barangay_48a', label: 'Barangay 48A' },
      { value: 'barangay_49m', label: 'Barangay 49M' },
      { value: 'barangay_49a', label: 'Barangay 49A' },
      { value: 'barangay_50', label: 'Barangay 50' },
      { value: 'barangay_51', label: 'Barangay 51' },
      { value: 'barangay_52', label: 'Barangay 52' },
      { value: 'barangay_53m', label: 'Barangay 53M' },
      { value: 'barangay_53a', label: 'Barangay 53A' },
      { value: 'barangay_53b', label: 'Barangay 53B' },
      { value: 'barangay_54m', label: 'Barangay 54M' },
      { value: 'barangay_54a', label: 'Barangay 54A' },
      { value: 'barangay_55', label: 'Barangay 55' },
      { value: 'barangay_56', label: 'Barangay 56' },
      { value: 'barangay_57', label: 'Barangay 57' },
      { value: 'barangay_58m', label: 'Barangay 58M' },
      { value: 'barangay_58a', label: 'Barangay 58A' },
      { value: 'barangay_59', label: 'Barangay 59' },
      { value: 'barangay_60', label: 'Barangay 60' },
      { value: 'barangay_61m', label: 'Barangay 61M' },
      { value: 'barangay_61a', label: 'Barangay 61A' },
      { value: 'barangay_62m', label: 'Barangay 62M' },
      { value: 'barangay_62a', label: 'Barangay 62A' },
      { value: 'barangay_62b', label: 'Barangay 62B' }
    ],
    bacoor: [
      { value: 'alima', label: 'Alima' },
      { value: 'aniban_i', label: 'Aniban I' },
      { value: 'aniban_ii', label: 'Aniban II' },
      { value: 'aniban_iii', label: 'Aniban III' },
      { value: 'aniban_iv', label: 'Aniban IV' },
      { value: 'aniban_v', label: 'Aniban V' },
      { value: 'banalo', label: 'Banalo' },
      { value: 'bayan_an', label: 'Bayanan' },
      { value: 'campo_santo', label: 'Campo Santo' },
      { value: 'daang_bukid', label: 'Daang Bukid' },
      { value: 'digman', label: 'Digman' },
      { value: 'dulong_bayan', label: 'Dulong Bayan' },
      { value: 'habay_i', label: 'Habay I' },
      { value: 'habay_ii', label: 'Habay II' },
      { value: 'kaingin', label: 'Kaingin' },
      { value: 'ligas_i', label: 'Ligas I' },
      { value: 'ligas_ii', label: 'Ligas II' },
      { value: 'ligas_iii', label: 'Ligas III' },
      { value: 'mabolo_i', label: 'Mabolo I' },
      { value: 'mabolo_ii', label: 'Mabolo II' },
      { value: 'mabolo_iii', label: 'Mabolo III' },
      { value: 'maliksi_i', label: 'Maliksi I' },
      { value: 'maliksi_ii', label: 'Maliksi II' },
      { value: 'maliksi_iii', label: 'Maliksi III' },
      { value: 'mambog_i', label: 'Mambog I' },
      { value: 'mambog_ii', label: 'Mambog II' },
      { value: 'mambog_iii', label: 'Mambog III' },
      { value: 'mambog_iv', label: 'Mambog IV' },
      { value: 'mambog_v', label: 'Mambog V' },
      { value: 'molino_i', label: 'Molino I' },
      { value: 'molino_ii', label: 'Molino II' },
      { value: 'molino_iii', label: 'Molino III' },
      { value: 'molino_iv', label: 'Molino IV' },
      { value: 'molino_v', label: 'Molino V' },
      { value: 'molino_vi', label: 'Molino VI' },
      { value: 'molino_vii', label: 'Molino VII' },
      { value: 'niog_i', label: 'Niog I' },
      { value: 'niog_ii', label: 'Niog II' },
      { value: 'niog_iii', label: 'Niog III' },
      { value: 'pf_espiritu_i', label: 'P. F. Espiritu I' },
      { value: 'pf_espiritu_ii', label: 'P. F. Espiritu II' },
      { value: 'pf_espiritu_iii', label: 'P. F. Espiritu III' },
      { value: 'pf_espiritu_iv', label: 'P. F. Espiritu IV' },
      { value: 'pf_espiritu_v', label: 'P. F. Espiritu V' },
      { value: 'pf_espiritu_vi', label: 'P. F. Espiritu VI' },
      { value: 'pf_espiritu_vii', label: 'P. F. Espiritu VII' },
      { value: 'pf_espiritu_viii', label: 'P. F. Espiritu VIII' },
      { value: 'queens_row_central', label: 'Queens Row Central' },
      { value: 'queens_row_east', label: 'Queens Row East' },
      { value: 'queens_row_west', label: 'Queens Row West' },
      { value: 'real_i', label: 'Real I' },
      { value: 'real_ii', label: 'Real II' },
      { value: 'salinas_i', label: 'Salinas I' },
      { value: 'salinas_ii', label: 'Salinas II' }
    ],
    carmona: [
      { value: 'abong_abong', label: 'Abong-Abong' },
      { value: 'bancal', label: 'Bancal' },
      { value: 'cabilang', label: 'Cabilang' },
      { value: 'gabutan', label: 'Gabutan' },
      { value: 'lamesa', label: 'Lamesa' },
      { value: 'mabuhay', label: 'Mabuhay' },
      { value: 'maduya', label: 'Maduya' },
      { value: 'mabolo', label: 'Mabolo' },
      { value: 'parang_1', label: 'Parang 1' },
      { value: 'parang_2', label: 'Parang 2' },
      { value: 'parang_3', label: 'Parang 3' },
      { value: 'poblacion_1', label: 'Poblacion 1' },
      { value: 'poblacion_2', label: 'Poblacion 2' },
      { value: 'poblacion_3', label: 'Poblacion 3' },
      { value: 'salvacion', label: 'Salvacion' }
    ],
    dasmarinas: [
      { value: 'burol', label: 'Burol' },
      { value: 'burol_i', label: 'Burol I' },
      { value: 'burol_ii', label: 'Burol II' },
      { value: 'burol_iii', label: 'Burol III' },
      { value: 'datu_esmael', label: 'Datu Esmael' },
      { value: 'emmanuel_bergado_i', label: 'Emmanuel Bergado I' },
      { value: 'emmanuel_bergado_ii', label: 'Emmanuel Bergado II' },
      { value: 'fatima_i', label: 'Fatima I' },
      { value: 'fatima_ii', label: 'Fatima II' },
      { value: 'fatima_iii', label: 'Fatima III' },
      { value: 'h_2', label: 'H-2' },
      { value: 'langkaan_i', label: 'Langkaan I' },
      { value: 'langkaan_ii', label: 'Langkaan II' },
      { value: 'luzviminda_i', label: 'Luzviminda I' },
      { value: 'luzviminda_ii', label: 'Luzviminda II' },
      { value: 'paliparan_i', label: 'Paliparan I' },
      { value: 'paliparan_ii', label: 'Paliparan II' },
      { value: 'paliparan_iii', label: 'Paliparan III' },
      { value: 'sabang', label: 'Sabang' },
      { value: 'saint_peter_i', label: 'Saint Peter I' },
      { value: 'saint_peter_ii', label: 'Saint Peter II' },
      { value: 'salawag', label: 'Salawag' },
      { value: 'salitran_i', label: 'Salitran I' },
      { value: 'salitran_ii', label: 'Salitran II' },
      { value: 'salitran_iii', label: 'Salitran III' },
      { value: 'salitran_iv', label: 'Salitran IV' },
      { value: 'sampaloc_i', label: 'Sampaloc I' },
      { value: 'sampaloc_ii', label: 'Sampaloc II' },
      { value: 'sampaloc_iii', label: 'Sampaloc III' },
      { value: 'sampaloc_iv', label: 'Sampaloc IV' },
      { value: 'sampaloc_v', label: 'Sampaloc V' },
      { value: 'san_agustin_i', label: 'San Agustin I' },
      { value: 'san_agustin_ii', label: 'San Agustin II' },
      { value: 'san_agustin_iii', label: 'San Agustin III' },
      { value: 'san_andres_i', label: 'San Andres I' },
      { value: 'san_andres_ii', label: 'San Andres II' },
      { value: 'san_antonio_de_padua_i', label: 'San Antonio de Padua I' },
      { value: 'san_antonio_de_padua_ii', label: 'San Antonio de Padua II' },
      { value: 'san_dionisio', label: 'San Dionisio' },
      { value: 'san_esteban', label: 'San Esteban' },
      { value: 'san_francisco_i', label: 'San Francisco I' },
      { value: 'san_francisco_ii', label: 'San Francisco II' },
      { value: 'san_isidro_labrador_i', label: 'San Isidro Labrador I' },
      { value: 'san_isidro_labrador_ii', label: 'San Isidro Labrador II' },
      { value: 'san_jose', label: 'San Jose' },
      { value: 'san_juan', label: 'San Juan' },
      { value: 'san_lorenzo_ruiz_i', label: 'San Lorenzo Ruiz I' },
      { value: 'san_lorenzo_ruiz_ii', label: 'San Lorenzo Ruiz II' },
      { value: 'san_luis_i', label: 'San Luis I' }
    ],
    general_trias: [
      { value: 'alingaro', label: 'Alingaro' },
      { value: 'arnaldo_poblacion', label: 'Arnaldo Poblacion' },
      { value: 'bacao_i', label: 'Bacao I' },
      { value: 'bacao_ii', label: 'Bacao II' },
      { value: 'bagumbayan_poblacion', label: 'Bagumbayan Poblacion' },
      { value: 'biclatan', label: 'Biclatan' },
      { value: 'buenavista_i', label: 'Buenavista I' },
      { value: 'buenavista_ii', label: 'Buenavista II' },
      { value: 'buenavista_iii', label: 'Buenavista III' },
      { value: 'corregidor_poblacion', label: 'Corregidor Poblacion' },
      { value: 'dulong_bayan_poblacion', label: 'Dulong Bayan Poblacion' },
      { value: 'gov_ferrer_poblacion', label: 'Gov. Ferrer Poblacion' },
      { value: 'javalera', label: 'Javalera' },
      { value: 'manggahan', label: 'Manggahan' },
      { value: 'navarro', label: 'Navarro' },
      { value: 'ninety_sixth_poblacion', label: 'Ninety Sixth Poblacion' },
      { value: 'panungyanan', label: 'Panungyanan' },
      { value: 'pasong_camachile_i', label: 'Pasong Camachile I' },
      { value: 'pasong_camachile_ii', label: 'Pasong Camachile II' },
      { value: 'pasong_kawayan_i', label: 'Pasong Kawayan I' },
      { value: 'pasong_kawayan_ii', label: 'Pasong Kawayan II' },
      { value: 'pinagtipunan', label: 'Pinagtipunan' },
      { value: 'prinza_poblacion', label: 'Prinza Poblacion' },
      { value: 'sampalucan_poblacion', label: 'Sampalucan Poblacion' },
      { value: 'san_francisco', label: 'San Francisco' },
      { value: 'san_gabriel_poblacion', label: 'San Gabriel Poblacion' },
      { value: 'san_juan_i', label: 'San Juan I' },
      { value: 'san_juan_ii', label: 'San Juan II' },
      { value: 'santa_clara', label: 'Santa Clara' },
      { value: 'santiago', label: 'Santiago' },
      { value: 'tapia', label: 'Tapia' },
      { value: 'tejero', label: 'Tejero' },
      { value: 'vibora_poblacion', label: 'Vibora Poblacion' }
    ],
    imus: [
      { value: 'alapan_i_a', label: 'Alapan I-A' },
      { value: 'alapan_i_b', label: 'Alapan I-B' },
      { value: 'alapan_i_c', label: 'Alapan I-C' },
      { value: 'alapan_ii_a', label: 'Alapan II-A' },
      { value: 'alapan_ii_b', label: 'Alapan II-B' },
      { value: 'anabu_i_a', label: 'Anabu I-A' },
      { value: 'anabu_i_b', label: 'Anabu I-B' },
      { value: 'anabu_i_c', label: 'Anabu I-C' },
      { value: 'anabu_i_d', label: 'Anabu I-D' },
      { value: 'anabu_i_e', label: 'Anabu I-E' },
      { value: 'anabu_i_f', label: 'Anabu I-F' },
      { value: 'anabu_i_g', label: 'Anabu I-G' },
      { value: 'anabu_ii_a', label: 'Anabu II-A' },
      { value: 'anabu_ii_b', label: 'Anabu II-B' },
      { value: 'anabu_ii_c', label: 'Anabu II-C' },
      { value: 'anabu_ii_d', label: 'Anabu II-D' },
      { value: 'anabu_ii_e', label: 'Anabu II-E' },
      { value: 'anabu_ii_f', label: 'Anabu II-F' },
      { value: 'bagong_silang', label: 'Bagong Silang' },
      { value: 'bayan_luma_i', label: 'Bayan Luma I' },
      { value: 'bayan_luma_ii', label: 'Bayan Luma II' },
      { value: 'bayan_luma_iii', label: 'Bayan Luma III' },
      { value: 'bayan_luma_iv', label: 'Bayan Luma IV' },
      { value: 'bayan_luma_ix', label: 'Bayan Luma IX' },
      { value: 'bayan_luma_v', label: 'Bayan Luma V' },
      { value: 'bayan_luma_vi', label: 'Bayan Luma VI' },
      { value: 'bayan_luma_vii', label: 'Bayan Luma VII' },
      { value: 'bayan_luma_viii', label: 'Bayan Luma VIII' },
      { value: 'bucandala_i', label: 'Bucandala I' },
      { value: 'bucandala_ii', label: 'Bucandala II' },
      { value: 'bucandala_iii', label: 'Bucandala III' },
      { value: 'bucandala_iv', label: 'Bucandala IV' },
      { value: 'bucandala_v', label: 'Bucandala V' },
      { value: 'buhay_na_tubig', label: 'Buhay na Tubig' },
      { value: 'carsadang_bago_i', label: 'Carsadang Bago I' },
      { value: 'carsadang_bago_ii', label: 'Carsadang Bago II' },
      { value: 'magdalo', label: 'Magdalo' },
      { value: 'maharlika', label: 'Maharlika' },
      { value: 'malagasang_i_a', label: 'Malagasang I-A' },
      { value: 'malagasang_i_b', label: 'Malagasang I-B' },
      { value: 'malagasang_i_c', label: 'Malagasang I-C' },
      { value: 'malagasang_i_d', label: 'Malagasang I-D' },
      { value: 'malagasang_i_e', label: 'Malagasang I-E' },
      { value: 'malagasang_i_f', label: 'Malagasang I-F' },
      { value: 'malagasang_i_g', label: 'Malagasang I-G' },
      { value: 'malagasang_ii_a', label: 'Malagasang II-A' },
      { value: 'malagasang_ii_b', label: 'Malagasang II-B' },
      { value: 'malagasang_ii_c', label: 'Malagasang II-C' },
      { value: 'malagasang_ii_d', label: 'Malagasang II-D' },
      { value: 'malagasang_ii_e', label: 'Malagasang II-E' },
      { value: 'malagasang_ii_f', label: 'Malagasang II-F' },
      { value: 'malagasang_ii_g', label: 'Malagasang II-G' }
    ],
    kawit: [
      { value: 'bagong_kalabaw', label: 'Bagong Kalabaw' },
      { value: 'binakayan', label: 'Binakayan' },
      { value: 'kaingen', label: 'Kaingen' },
      { value: 'luzviminda', label: 'Luzviminda' },
      { value: 'magdalo', label: 'Magdalo' },
      { value: 'mahabang_limas', label: 'Mahabang Limas' },
      { value: 'maragondon', label: 'Maragondon' },
      { value: 'poblacion', label: 'Poblacion' },
      { value: 'san_isidro', label: 'San Isidro' },
      { value: 'toclong', label: 'Toclong' },
      { value: 'timalan', label: 'Timalan' },
      { value: 'wakas', label: 'Wakas' }
    ],
    tagaytay: [
      { value: 'asuncion', label: 'Asuncion' },
      { value: 'bagong_tubig', label: 'Bagong Tubig' },
      { value: 'balitbalit', label: 'Balitbalit' },
      { value: 'caloocan', label: 'Caloocan' },
      { value: 'cavinito', label: 'Cavinito' },
      { value: 'dapdap', label: 'Dapdap' },
      { value: 'dita', label: 'Dita' },
      { value: 'francisco', label: 'Francisco' },
      { value: 'guinhawa', label: 'Guinhawa' },
      { value: 'halang', label: 'Halang' },
      { value: 'harrison', label: 'Harrison' },
      { value: 'jose_rizal', label: 'Jose Rizal' },
      { value: 'kaybagal_north', label: 'Kaybagal North' },
      { value: 'kaybagal_south', label: 'Kaybagal South' },
      { value: 'mag-asawang_sapa', label: 'Mag-asawang Sapa' },
      { value: 'maharlika_east', label: 'Maharlika East' },
      { value: 'maharlika_west', label: 'Maharlika West' },
      { value: 'maitim', label: 'Maitim' },
      { value: 'manalac', label: 'Manalac' },
      { value: 'mendez', label: 'Mendez' },
      { value: 'neogan', label: 'Neogan' },
      { value: 'panes', label: 'Panes' },
      { value: 'poblacion', label: 'Poblacion' },
      { value: 'sambal', label: 'Sambal' },
      { value: 'san_jose', label: 'San Jose' },
      { value: 'san_nicolas', label: 'San Nicolas' },
      { value: 'san_roque', label: 'San Roque' },
      { value: 'santo_domingo', label: 'Santo Domingo' },
      { value: 'santo_nino', label: 'Santo Niño' },
      { value: 'sikat', label: 'Sikat' },
      { value: 'silang', label: 'Silang' },
      { value: 'summit', label: 'Summit' },
      { value: 'talahib', label: 'Talahib' },
      { value: 'tolentino', label: 'Tolentino' },
      { value: 'tubuan', label: 'Tubuan' },
      { value: 'zambal', label: 'Zambal' }
    ],
    maragondon: [
      { value: 'bucal_i', label: 'Bucal I' },
      { value: 'bucal_ii', label: 'Bucal II' },
      { value: 'bucal_iii_a', label: 'Bucal III A' },
      { value: 'bucal_iii_b', label: 'Bucal III B' },
      { value: 'bucal_iv_a', label: 'Bucal IV A' },
      { value: 'bucal_iv_b', label: 'Bucal IV B' },
      { value: 'caingin_poblacion', label: 'Caingin Poblacion' },
      { value: 'garita_i_a', label: 'Garita I A' },
      { value: 'garita_i_b', label: 'Garita I B' },
      { value: 'layong_mabilog', label: 'Layong Mabilog' },
      { value: 'mabato', label: 'Mabato' },
      { value: 'pantihan_i', label: 'Pantihan I' },
      { value: 'pantihan_ii', label: 'Pantihan II' },
      { value: 'pantihan_iii', label: 'Pantihan III' },
      { value: 'pantihan_iv', label: 'Pantihan IV' },
      { value: 'patungan', label: 'Patungan' },
      { value: 'pinagsanhan_i_a', label: 'Pinagsanhan I A' },
      { value: 'pinagsanhan_i_b', label: 'Pinagsanhan I B' },
      { value: 'poblacion_i_a', label: 'Poblacion I A' },
      { value: 'poblacion_i_b', label: 'Poblacion I B' },
      { value: 'poblacion_ii_a', label: 'Poblacion II A' },
      { value: 'poblacion_ii_b', label: 'Poblacion II B' },
      { value: 'san_miguel_i_a', label: 'San Miguel I A' },
      { value: 'san_miguel_i_b', label: 'San Miguel I B' },
      { value: 'talipusngo', label: 'Talipusngo' },
      { value: 'tulay_kanluran', label: 'Tulay Kanluran' },
      { value: 'tulay_silangan', label: 'Tulay Silangan' }
    ],
    naic: [
      { value: 'bagong_karsada', label: 'Bagong Karsada' },
      { value: 'balsahan', label: 'Balsahan' },
      { value: 'bancaan', label: 'Bancaan' },
      { value: 'bucana_malaki', label: 'Bucana Malaki' },
      { value: 'bucana_sasahan', label: 'Bucana Sasahan' },
      { value: 'calubcob', label: 'Calubcob' },
      { value: 'capt_c_nazareno', label: 'Capt. C. Nazareno' },
      { value: 'gomez_zamora', label: 'Gomez-Zamora' },
      { value: 'halang', label: 'Halang' },
      { value: 'humbac', label: 'Humbac' },
      { value: 'ibayo_estacion', label: 'Ibayo Estacion' },
      { value: 'ibayo_silangan', label: 'Ibayo Silangan' },
      { value: 'kanluran', label: 'Kanluran' },
      { value: 'labac', label: 'Labac' },
      { value: 'latoria', label: 'Latoria' },
      { value: 'mabolo', label: 'Mabolo' },
      { value: 'makina', label: 'Makina' },
      { value: 'malainen_bago', label: 'Malainen Bago' },
      { value: 'malainen_luma', label: 'Malainen Luma' },
      { value: 'molino', label: 'Molino' },
      { value: 'munting_mapino', label: 'Munting Mapino' },
      { value: 'muzon', label: 'Muzon' },
      { value: 'palangue_1', label: 'Palangue 1' },
      { value: 'palangue_2_3', label: 'Palangue 2 & 3' },
      { value: 'sabang', label: 'Sabang' },
      { value: 'san_roque', label: 'San Roque' },
      { value: 'santulan', label: 'Santulan' },
      { value: 'sapa', label: 'Sapa' },
      { value: 'timalan_balsahan', label: 'Timalan Balsahan' },
      { value: 'timalan_concepcion', label: 'Timalan Concepcion' }
    ],
    magallanes: [
      { value: 'baliwag', label: 'Baliwag' },
      { value: 'barangay_1', label: 'Barangay 1' },
      { value: 'barangay_2', label: 'Barangay 2' },
      { value: 'barangay_3', label: 'Barangay 3' },
      { value: 'barangay_4', label: 'Barangay 4' },
      { value: 'barangay_5', label: 'Barangay 5' },
      { value: 'bendita_i', label: 'Bendita I' },
      { value: 'bendita_ii', label: 'Bendita II' },
      { value: 'caluangan', label: 'Caluangan' },
      { value: 'kabulusan', label: 'Kabulusan' },
      { value: 'medina', label: 'Medina' },
      { value: 'pacheco', label: 'Pacheco' },
      { value: 'ramirez', label: 'Ramirez' },
      { value: 'san_agustin', label: 'San Agustin' },
      { value: 'tua', label: 'Tua' },
      { value: 'urdaneta', label: 'Urdaneta' }
    ],
    mendez: [
      { value: 'anuling_cerca_i', label: 'Anuling Cerca I' },
      { value: 'anuling_cerca_ii', label: 'Anuling Cerca II' },
      { value: 'anuling_lejos_i', label: 'Anuling Lejos I' },
      { value: 'anuling_lejos_ii', label: 'Anuling Lejos II' },
      { value: 'asis_i', label: 'Asis I' },
      { value: 'asis_ii', label: 'Asis II' },
      { value: 'asis_iii', label: 'Asis III' },
      { value: 'banayad', label: 'Banayad' },
      { value: 'bukal', label: 'Bukal' },
      { value: 'galicia_i', label: 'Galicia I' },
      { value: 'galicia_ii', label: 'Galicia II' },
      { value: 'galicia_iii', label: 'Galicia III' },
      { value: 'miguel_mojica', label: 'Miguel Mojica' },
      { value: 'palocpoc_i', label: 'Palocpoc I' },
      { value: 'palocpoc_ii', label: 'Palocpoc II' },
      { value: 'panungyan_i', label: 'Panungyan I' },
      { value: 'panungyan_ii', label: 'Panungyan II' },
      { value: 'poblacion_i', label: 'Poblacion I' },
      { value: 'poblacion_ii', label: 'Poblacion II' },
      { value: 'poblacion_iii', label: 'Poblacion III' },
      { value: 'poblacion_iv', label: 'Poblacion IV' },
      { value: 'poblacion_v', label: 'Poblacion V' },
      { value: 'poblacion_vi', label: 'Poblacion VI' },
      { value: 'poblacion_vii', label: 'Poblacion VII' }
    ],
    ternate: [
      { value: 'bucana', label: 'Bucana' },
      { value: 'poblacion_i', label: 'Poblacion I' },
      { value: 'poblacion_i_a', label: 'Poblacion I A' },
      { value: 'poblacion_ii', label: 'Poblacion II' },
      { value: 'poblacion_iii', label: 'Poblacion III' },
      { value: 'san_jose', label: 'San Jose' },
      { value: 'san_juan_i', label: 'San Juan I' },
      { value: 'san_juan_ii', label: 'San Juan II' },
      { value: 'sapang_i', label: 'Sapang I' },
      { value: 'sapang_ii', label: 'Sapang II' }
    ],
    noveleta: [
      { value: 'magdiwang', label: 'Magdiwang' },
      { value: 'poblacion', label: 'Poblacion' },
      { value: 'salcedo_i', label: 'Salcedo I' },
      { value: 'salcedo_ii', label: 'Salcedo II' },
      { value: 'san_antonio_i', label: 'San Antonio I' },
      { value: 'san_antonio_ii', label: 'San Antonio II' },
      { value: 'san_jose_i', label: 'San Jose I' },
      { value: 'san_jose_ii', label: 'San Jose II' },
      { value: 'san_juan_i', label: 'San Juan I' },
      { value: 'san_juan_ii', label: 'San Juan II' },
      { value: 'san_rafael_i', label: 'San Rafael I' },
      { value: 'san_rafael_ii', label: 'San Rafael II' },
      { value: 'san_rafael_iii', label: 'San Rafael III' },
      { value: 'san_rafael_iv', label: 'San Rafael IV' },
      { value: 'santa_rosa_i', label: 'Santa Rosa I' },
      { value: 'santa_rosa_ii', label: 'Santa Rosa II' }
    ],
    rosario: [
      { value: 'bagbag_i', label: 'Bagbag I' },
      { value: 'bagbag_ii', label: 'Bagbag II' },
      { value: 'kanluran', label: 'Kanluran' },
      { value: 'ligtong_i', label: 'Ligtong I' },
      { value: 'ligtong_ii', label: 'Ligtong II' },
      { value: 'ligtong_iii', label: 'Ligtong III' },
      { value: 'ligtong_iv', label: 'Ligtong IV' },
      { value: 'muzon_i', label: 'Muzon I' },
      { value: 'muzon_ii', label: 'Muzon II' },
      { value: 'poblacion', label: 'Poblacion' },
      { value: 'sapa_i', label: 'Sapa I' },
      { value: 'sapa_ii', label: 'Sapa II' },
      { value: 'sapa_iii', label: 'Sapa III' },
      { value: 'sapa_iv', label: 'Sapa IV' },
      { value: 'silangan_i', label: 'Silangan I' },
      { value: 'silangan_ii', label: 'Silangan II' },
      { value: 'tejeros_convention', label: 'Tejeros Convention' },
      { value: 'wawa_i', label: 'Wawa I' },
      { value: 'wawa_ii', label: 'Wawa II' },
      { value: 'wawa_iii', label: 'Wawa III' }
    ],
    silang: [
      { value: 'acacia', label: 'Acacia' },
      { value: 'adlas', label: 'Adlas' },
      { value: 'anahaw_i', label: 'Anahaw I' },
      { value: 'anahaw_ii', label: 'Anahaw II' },
      { value: 'balite_i', label: 'Balite I' },
      { value: 'balite_ii', label: 'Balite II' },
      { value: 'balubad', label: 'Balubad' },
      { value: 'banaba', label: 'Banaba' },
      { value: 'barangay_i', label: 'Barangay I' },
      { value: 'barangay_ii', label: 'Barangay II' },
      { value: 'barangay_iii', label: 'Barangay III' },
      { value: 'barangay_iv', label: 'Barangay IV' },
      { value: 'barangay_v', label: 'Barangay V' },
      { value: 'batas', label: 'Batas' },
      { value: 'biga_i', label: 'Biga I' },
      { value: 'biga_ii', label: 'Biga II' },
      { value: 'biluso', label: 'Biluso' },
      { value: 'bucal', label: 'Bucal' },
      { value: 'buho', label: 'Buho' },
      { value: 'bulihan', label: 'Bulihan' },
      { value: 'cabangaan', label: 'Cabangaan' },
      { value: 'carmen', label: 'Carmen' },
      { value: 'hoyo', label: 'Hoyo' },
      { value: 'hukay', label: 'Hukay' },
      { value: 'iba', label: 'Iba' },
      { value: 'inchican', label: 'Inchican' },
      { value: 'ipil_i', label: 'Ipil I' },
      { value: 'ipil_ii', label: 'Ipil II' },
      { value: 'kalubkob', label: 'Kalubkob' },
      { value: 'kaong', label: 'Kaong' },
      { value: 'lalaan_i', label: 'Lalaan I' },
      { value: 'lalaan_ii', label: 'Lalaan II' },
      { value: 'litlit', label: 'Litlit' },
      { value: 'lucsuhin', label: 'Lucsuhin' },
      { value: 'lumil', label: 'Lumil' },
      { value: 'maguyam', label: 'Maguyam' },
      { value: 'malabag', label: 'Malabag' },
      { value: 'malaking_tatyao', label: 'Malaking Tatyao' },
      { value: 'mataas_na_burol', label: 'Mataas na Burol' },
      { value: 'munting_ilog', label: 'Munting Ilog' },
      { value: 'narra_i', label: 'Narra I' },
      { value: 'narra_ii', label: 'Narra II' },
      { value: 'narra_iii', label: 'Narra III' },
      { value: 'paligawan', label: 'Paligawan' },
      { value: 'pasong_langka', label: 'Pasong Langka' },
      { value: 'pooc_i', label: 'Pooc I' },
      { value: 'pooc_ii', label: 'Pooc II' },
      { value: 'pulong_bunga', label: 'Pulong Bunga' },
      { value: 'pulong_saging', label: 'Pulong Saging' },
      { value: 'puting_kahoy', label: 'Puting Kahoy' },
      { value: 'sabutan', label: 'Sabutan' },
      { value: 'san_miguel_i', label: 'San Miguel I' },
      { value: 'san_miguel_ii', label: 'San Miguel II' },
      { value: 'san_vicente_i', label: 'San Vicente I' },
      { value: 'san_vicente_ii', label: 'San Vicente II' },
      { value: 'santol', label: 'Santol' }
    ],
    alfonso: [
      { value: 'amuyong', label: 'Amuyong' },
      { value: 'barangay_i_pob', label: 'Barangay I (Poblacion)' },
      { value: 'barangay_ii_pob', label: 'Barangay II (Poblacion)' },
      { value: 'barangay_iii_pob', label: 'Barangay III (Poblacion)' },
      { value: 'barangay_iv_pob', label: 'Barangay IV (Poblacion)' },
      { value: 'barangay_v_pob', label: 'Barangay V (Poblacion)' },
      { value: 'bilog', label: 'Bilog' },
      { value: 'buck_estate', label: 'Buck Estate' },
      { value: 'esperanza_ibaba', label: 'Esperanza Ibaba' },
      { value: 'esperanza_ilaya', label: 'Esperanza Ilaya' },
      { value: 'kaysuyo', label: 'Kaysuyo' },
      { value: 'kaytitinga_i', label: 'Kaytitinga I' },
      { value: 'kaytitinga_ii', label: 'Kaytitinga II' },
      { value: 'kaytitinga_iii', label: 'Kaytitinga III' },
      { value: 'luksuhin_ibaba', label: 'Luksuhin Ibaba' },
      { value: 'luksuhin_ilaya', label: 'Luksuhin Ilaya' },
      { value: 'mangas_i', label: 'Mangas I' },
      { value: 'mangas_ii', label: 'Mangas II' },
      { value: 'marahan_i', label: 'Marahan I' },
      { value: 'marahan_ii', label: 'Marahan II' },
      { value: 'matagbak_i', label: 'Matagbak I' },
      { value: 'matagbak_ii', label: 'Matagbak II' },
      { value: 'pajo', label: 'Pajo' },
      { value: 'palumlum', label: 'Palumlum' },
      { value: 'santa_teresa', label: 'Santa Teresa' },
      { value: 'sikat', label: 'Sikat' },
      { value: 'sinaliw_malaki', label: 'Sinaliw Malaki' },
      { value: 'sinaliw_na_munti', label: 'Sinaliw na Munti' },
      { value: 'sulsugin', label: 'Sulsugin' },
      { value: 'taywanak_ibaba', label: 'Taywanak Ibaba' },
      { value: 'taywanak_ilaya', label: 'Taywanak Ilaya' },
      { value: 'upli', label: 'Upli' }
    ],
    amadeo: [
      { value: 'banaybanay', label: 'Banaybanay' },
      { value: 'barangay_i_pob', label: 'Barangay I (Poblacion)' },
      { value: 'barangay_ii_pob', label: 'Barangay II (Poblacion)' },
      { value: 'barangay_iii_pob', label: 'Barangay III (Poblacion)' },
      { value: 'barangay_iv_pob', label: 'Barangay IV (Poblacion)' },
      { value: 'barangay_v_pob', label: 'Barangay V (Poblacion)' },
      { value: 'barangay_vi_pob', label: 'Barangay VI (Poblacion)' },
      { value: 'barangay_vii_pob', label: 'Barangay VII (Poblacion)' },
      { value: 'barangay_viii_pob', label: 'Barangay VIII (Poblacion)' },
      { value: 'barangay_ix_pob', label: 'Barangay IX (Poblacion)' },
      { value: 'barangay_x_pob', label: 'Barangay X (Poblacion)' },
      { value: 'barangay_xi_pob', label: 'Barangay XI (Poblacion)' },
      { value: 'barangay_xii_pob', label: 'Barangay XII (Poblacion)' },
      { value: 'bucal', label: 'Bucal' },
      { value: 'buho', label: 'Buho' },
      { value: 'dagatan', label: 'Dagatan' },
      { value: 'halang', label: 'Halang' },
      { value: 'loma', label: 'Loma' },
      { value: 'maitim_i', label: 'Maitim I' },
      { value: 'maymangga', label: 'Maymangga' },
      { value: 'minantok_kanluran', label: 'Minantok Kanluran' },
      { value: 'minantok_silangan', label: 'Minantok Silangan' },
      { value: 'pangil', label: 'Pangil' },
      { value: 'salaban', label: 'Salaban' },
      { value: 'talon', label: 'Talon' },
      { value: 'tamacan', label: 'Tamacan' }
    ],
    general_emilio_aguinaldo: [
      { value: 'a_dalusag', label: 'A. Dalusag' },
      { value: 'batas_dao', label: 'Batas Dao' },
      { value: 'castanos_cerca', label: 'Castaños Cerca' },
      { value: 'castanos_lejos', label: 'Castaños Lejos' },
      { value: 'kabulusan', label: 'Kabulusan' },
      { value: 'kaymisas', label: 'Kaymisas' },
      { value: 'kaypaaba', label: 'Kaypaaba' },
      { value: 'lumipa', label: 'Lumipa' },
      { value: 'narvaez', label: 'Narvaez' },
      { value: 'poblacion_i', label: 'Poblacion I' },
      { value: 'poblacion_ii', label: 'Poblacion II' },
      { value: 'poblacion_iii', label: 'Poblacion III' },
      { value: 'poblacion_iv', label: 'Poblacion IV' },
      { value: 'tabora', label: 'Tabora' }
    ],
    general_mariano_alvarez: [
      { value: 'aldiano_olaes', label: 'Aldiano Olaes' },
      { value: 'barangay_1_pob', label: 'Barangay 1 Poblacion' },
      { value: 'barangay_2_pob', label: 'Barangay 2 Poblacion' },
      { value: 'barangay_3_pob', label: 'Barangay 3 Poblacion' },
      { value: 'barangay_4_pob', label: 'Barangay 4 Poblacion' },
      { value: 'barangay_5_pob', label: 'Barangay 5 Poblacion' },
      { value: 'benjamin_tirona', label: 'Benjamin Tirona' },
      { value: 'bernardo_pulido', label: 'Bernardo Pulido' },
      { value: 'epifanio_malia', label: 'Epifanio Malia' },
      { value: 'fiorello_calimag', label: 'Fiorello Calimag' },
      { value: 'francisco_reyes', label: 'Francisco Reyes' },
      { value: 'francisco_de_castro', label: 'Francisco De Castro' },
      { value: 'gavino_maderan', label: 'Gavino Maderan' },
      { value: 'gregoria_de_jesus', label: 'Gregoria De Jesus' },
      { value: 'inocencio_salud', label: 'Inocencio Salud' },
      { value: 'jacinto_lumbreras', label: 'Jacinto Lumbreras' },
      { value: 'kapitan_kua', label: 'Kapitan Kua' },
      { value: 'koronel_jose_p_elises', label: 'Koronel Jose P. Elises' },
      { value: 'macario_dacon', label: 'Macario Dacon' },
      { value: 'marcelino_memije', label: 'Marcelino Memije' },
      { value: 'nicolasa_virata', label: 'Nicolasa Virata' },
      { value: 'pantaleon_granados', label: 'Pantaleon Granados' },
      { value: 'ramon_cruz', label: 'Ramon Cruz' },
      { value: 'san_gabriel', label: 'San Gabriel' },
      { value: 'san_jose', label: 'San Jose' },
      { value: 'severino_de_las_alas', label: 'Severino De Las Alas' },
      { value: 'tiniente_tiago', label: 'Tiniente Tiago' }
    ],
    indang: [
      { value: 'agus_us', label: 'Agus-us' },
      { value: 'alulod', label: 'Alulod' },
      { value: 'banaba_cerca', label: 'Banaba Cerca' },
      { value: 'banaba_lejos', label: 'Banaba Lejos' },
      { value: 'bancod', label: 'Bancod' },
      { value: 'barangay_1_pob', label: 'Barangay 1 (Poblacion)' },
      { value: 'barangay_2_pob', label: 'Barangay 2 (Poblacion)' },
      { value: 'barangay_3_pob', label: 'Barangay 3 (Poblacion)' },
      { value: 'barangay_4_pob', label: 'Barangay 4 (Poblacion)' },
      { value: 'buna_cerca', label: 'Buna Cerca' },
      { value: 'buna_lejos_i', label: 'Buna Lejos I' },
      { value: 'buna_lejos_ii', label: 'Buna Lejos II' },
      { value: 'calumpang_cerca', label: 'Calumpang Cerca' },
      { value: 'calumpang_lejos_i', label: 'Calumpang Lejos I' },
      { value: 'carasuchi', label: 'Carasuchi' },
      { value: 'daine_i', label: 'Daine I' },
      { value: 'daine_ii', label: 'Daine II' },
      { value: 'guyam_malaki', label: 'Guyam Malaki' },
      { value: 'guyam_munti', label: 'Guyam Munti' },
      { value: 'harasan', label: 'Harasan' },
      { value: 'kayquit_i', label: 'Kayquit I' },
      { value: 'kayquit_ii', label: 'Kayquit II' },
      { value: 'kayquit_iii', label: 'Kayquit III' },
      { value: 'kaytambog', label: 'Kaytambog' },
      { value: 'kaytapos', label: 'Kaytapos' },
      { value: 'limbon', label: 'Limbon' },
      { value: 'lumampong_balagbag', label: 'Lumampong Balagbag' },
      { value: 'lumampong_bato', label: 'Lumampong Bato' },
      { value: 'mataas_na_lupa', label: 'Mataas na Lupa' },
      { value: 'pulo', label: 'Pulo' },
      { value: 'tabon', label: 'Tabon' },
      { value: 'tambo_balagbag', label: 'Tambo Balagbag' },
      { value: 'tambo_ilaya', label: 'Tambo Ilaya' },
      { value: 'tambo_kulit', label: 'Tambo Kulit' },
      { value: 'tambo_malaki', label: 'Tambo Malaki' },
      { value: 'toong', label: 'Toong' }
    ],
    tanza: [
      { value: 'amaya_i', label: 'Amaya I' },
      { value: 'amaya_ii', label: 'Amaya II' },
      { value: 'amaya_iii', label: 'Amaya III' },
      { value: 'amaya_iv', label: 'Amaya IV' },
      { value: 'amaya_v', label: 'Amaya V' },
      { value: 'amaya_vi', label: 'Amaya VI' },
      { value: 'amaya_vii', label: 'Amaya VII' },
      { value: 'bagtas', label: 'Bagtas' },
      { value: 'biga', label: 'Biga' },
      { value: 'biwas', label: 'Biwas' },
      { value: 'bucal', label: 'Bucal' },
      { value: 'bunga', label: 'Bunga' },
      { value: 'calibuyo', label: 'Calibuyo' },
      { value: 'capipisa', label: 'Capipisa' },
      { value: 'daang_amaya_i', label: 'Daang Amaya I' },
      { value: 'daang_amaya_ii', label: 'Daang Amaya II' },
      { value: 'daang_amaya_iii', label: 'Daang Amaya III' },
      { value: 'halayhay', label: 'Halayhay' },
      { value: 'julugan_i', label: 'Julugan I' },
      { value: 'julugan_ii', label: 'Julugan II' },
      { value: 'julugan_iii', label: 'Julugan III' },
      { value: 'julugan_iv', label: 'Julugan IV' },
      { value: 'julugan_v', label: 'Julugan V' },
      { value: 'julugan_vi', label: 'Julugan VI' },
      { value: 'julugan_vii', label: 'Julugan VII' },
      { value: 'julugan_viii', label: 'Julugan VIII' },
      { value: 'lambingan', label: 'Lambingan' },
      { value: 'mulawin', label: 'Mulawin' },
      { value: 'paradahan_i', label: 'Paradahan I' },
      { value: 'paradahan_ii', label: 'Paradahan II' },
      { value: 'poblacion_i', label: 'Poblacion I' },
      { value: 'poblacion_ii', label: 'Poblacion II' },
      { value: 'poblacion_iii', label: 'Poblacion III' },
      { value: 'poblacion_iv', label: 'Poblacion IV' },
      { value: 'punta_i', label: 'Punta I' },
      { value: 'punta_ii', label: 'Punta II' },
      { value: 'sahud_ulan', label: 'Sahud Ulan' },
      { value: 'sanja_mayor', label: 'Sanja Mayor' },
      { value: 'santol', label: 'Santol' },
      { value: 'tanauan', label: 'Tanauan' },
      { value: 'tres_cruses', label: 'Tres Cruses' }
    ],
    trece_martires: [
      { value: 'aguado', label: 'Aguado' },
      { value: 'cabezas', label: 'Cabezas' },
      { value: 'cabuco', label: 'Cabuco' },
      { value: 'conchu', label: 'Conchu' },
      { value: 'de_ocampo', label: 'De Ocampo' },
      { value: 'gregorio', label: 'Gregorio' },
      { value: 'inocencio', label: 'Inocencio' },
      { value: 'lallana', label: 'Lallana' },
      { value: 'lapidario', label: 'Lapidario' },
      { value: 'luciano', label: 'Luciano' },
      { value: 'osorio', label: 'Osorio' },
      { value: 'perez', label: 'Perez' },
      { value: 'san_agustin', label: 'San Agustin' }
    ]
  };

  return barangaysByCity[cityCode] || [];
};
