// Philippine Location Data with Province → City → Barangay Hierarchy
// This provides cascading location selectors for proper address entry

export const COUNTRIES = [
  { value: 'PH', label: 'Philippines' },
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'AU', label: 'Australia' },
  { value: 'JP', label: 'Japan' },
  { value: 'SG', label: 'Singapore' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'TH', label: 'Thailand' },
  { value: 'OTHERS', label: 'Others' }
];

// Philippine Provinces
export const PHILIPPINE_PROVINCES = [
  { value: 'cavite', label: 'Cavite' },
  { value: 'laguna', label: 'Laguna' },
  { value: 'batangas', label: 'Batangas' },
  { value: 'rizal', label: 'Rizal' },
  { value: 'quezon', label: 'Quezon' },
  { value: 'metro_manila', label: 'Metro Manila' },
  { value: 'bulacan', label: 'Bulacan' },
  { value: 'pampanga', label: 'Pampanga' },
  { value: 'bataan', label: 'Bataan' },
  { value: 'zambales', label: 'Zambales' },
  { value: 'tarlac', label: 'Tarlac' },
  { value: 'nueva_ecija', label: 'Nueva Ecija' },
  { value: 'pangasinan', label: 'Pangasinan' },
  { value: 'la_union', label: 'La Union' },
  { value: 'ilocos_norte', label: 'Ilocos Norte' },
  { value: 'ilocos_sur', label: 'Ilocos Sur' },
  { value: 'abra', label: 'Abra' },
  { value: 'apayao', label: 'Apayao' },
  { value: 'kalinga', label: 'Kalinga' },
  { value: 'mountain_province', label: 'Mountain Province' },
  { value: 'benguet', label: 'Benguet' },
  { value: 'ifugao', label: 'Ifugao' },
  { value: 'cagayan', label: 'Cagayan' },
  { value: 'isabela', label: 'Isabela' },
  { value: 'nueva_vizcaya', label: 'Nueva Vizcaya' },
  { value: 'quirino', label: 'Quirino' },
  { value: 'aurora', label: 'Aurora' },
  { value: 'batanes', label: 'Batanes' },
  { value: 'bicol_albay', label: 'Albay' },
  { value: 'bicol_camarines_norte', label: 'Camarines Norte' },
  { value: 'bicol_camarines_sur', label: 'Camarines Sur' },
  { value: 'bicol_catanduanes', label: 'Catanduanes' },
  { value: 'bicol_masbate', label: 'Masbate' },
  { value: 'bicol_sorsogon', label: 'Sorsogon' },
  { value: 'oriental_mindoro', label: 'Oriental Mindoro' },
  { value: 'occidental_mindoro', label: 'Occidental Mindoro' },
  { value: 'marinduque', label: 'Marinduque' },
  { value: 'romblon', label: 'Romblon' },
  { value: 'palawan', label: 'Palawan' },
  { value: 'aklan', label: 'Aklan' },
  { value: 'antique', label: 'Antique' },
  { value: 'capiz', label: 'Capiz' },
  { value: 'iloilo', label: 'Iloilo' },
  { value: 'guimaras', label: 'Guimaras' },
  { value: 'negros_occidental', label: 'Negros Occidental' },
  { value: 'negros_oriental', label: 'Negros Oriental' },
  { value: 'cebu', label: 'Cebu' },
  { value: 'bohol', label: 'Bohol' },
  { value: 'siquijor', label: 'Siquijor' },
  { value: 'leyte', label: 'Leyte' },
  { value: 'southern_leyte', label: 'Southern Leyte' },
  { value: 'biliran', label: 'Biliran' },
  { value: 'samar', label: 'Samar' },
  { value: 'eastern_samar', label: 'Eastern Samar' },
  { value: 'northern_samar', label: 'Northern Samar' },
  { value: 'western_samar', label: 'Western Samar' },
  { value: 'davao_del_norte', label: 'Davao del Norte' },
  { value: 'davao_del_sur', label: 'Davao del Sur' },
  { value: 'davao_oriental', label: 'Davao Oriental' },
  { value: 'davao_occidental', label: 'Davao Occidental' },
  { value: 'davao_de_oro', label: 'Davao de Oro' },
  { value: 'cotabato', label: 'Cotabato' },
  { value: 'south_cotabato', label: 'South Cotabato' },
  { value: 'sultan_kudarat', label: 'Sultan Kudarat' },
  { value: 'sarangani', label: 'Sarangani' },
  { value: 'agusan_del_norte', label: 'Agusan del Norte' },
  { value: 'agusan_del_sur', label: 'Agusan del Sur' },
  { value: 'surigao_del_norte', label: 'Surigao del Norte' },
  { value: 'surigao_del_sur', label: 'Surigao del Sur' },
  { value: 'dinagat_islands', label: 'Dinagat Islands' },
  { value: 'bukidnon', label: 'Bukidnon' },
  { value: 'camiguin', label: 'Camiguin' },
  { value: 'misamis_oriental', label: 'Misamis Oriental' },
  { value: 'misamis_occidental', label: 'Misamis Occidental' },
  { value: 'lanao_del_norte', label: 'Lanao del Norte' },
  { value: 'lanao_del_sur', label: 'Lanao del Sur' },
  { value: 'basilan', label: 'Basilan' },
  { value: 'sulu', label: 'Sulu' },
  { value: 'tawi_tawi', label: 'Tawi-Tawi' },
  { value: 'zamboanga_del_norte', label: 'Zamboanga del Norte' },
  { value: 'zamboanga_del_sur', label: 'Zamboanga del Sur' },
  { value: 'zamboanga_sibugay', label: 'Zamboanga Sibugay' }
];

// Cities by Province - Comprehensive Data
export const CITIES_BY_PROVINCE = {
  cavite: [
    { value: 'bacoor', label: 'Bacoor' },
    { value: 'carmona', label: 'Carmona' },
    { value: 'cavite_city', label: 'Cavite City' },
    { value: 'dasmarinas', label: 'Dasmariñas' },
    { value: 'general_emilio_aguinaldo', label: 'General Emilio Aguinaldo' },
    { value: 'general_mariano_alvarez', label: 'General Mariano Alvarez' },
    { value: 'general_trias', label: 'General Trias' },
    { value: 'imus', label: 'Imus' },
    { value: 'indang', label: 'Indang' },
    { value: 'kawit', label: 'Kawit' },
    { value: 'magallanes', label: 'Magallanes' },
    { value: 'maragondon', label: 'Maragondon' },
    { value: 'mendez', label: 'Mendez' },
    { value: 'naic', label: 'Naic' },
    { value: 'noveleta', label: 'Noveleta' },
    { value: 'rosario', label: 'Rosario' },
    { value: 'silang', label: 'Silang' },
    { value: 'tagaytay', label: 'Tagaytay' },
    { value: 'tanza', label: 'Tanza' },
    { value: 'ternate', label: 'Ternate' },
    { value: 'trece_martires', label: 'Trece Martires' }
  ],
  laguna: [
    { value: 'alaminos', label: 'Alaminos' },
    { value: 'bay', label: 'Bay' },
    { value: 'binan', label: 'Biñan' },
    { value: 'cabuyao', label: 'Cabuyao' },
    { value: 'calamba', label: 'Calamba' },
    { value: 'calauan', label: 'Calauan' },
    { value: 'cavinti', label: 'Cavinti' },
    { value: 'famy', label: 'Famy' },
    { value: 'kalayaan', label: 'Kalayaan' },
    { value: 'liliw', label: 'Liliw' },
    { value: 'los_banos', label: 'Los Baños' },
    { value: 'luisiana', label: 'Luisiana' },
    { value: 'lumban', label: 'Lumban' },
    { value: 'majayay', label: 'Majayjay' },
    { value: 'nagcarlan', label: 'Nagcarlan' },
    { value: 'paete', label: 'Paete' },
    { value: 'pagsanjan', label: 'Pagsanjan' },
    { value: 'pakil', label: 'Pakil' },
    { value: 'pangil', label: 'Pangil' },
    { value: 'pila', label: 'Pila' },
    { value: 'rizal', label: 'Rizal' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'siniloan', label: 'Siniloan' },
    { value: 'victoria', label: 'Victoria' }
  ],
  batangas: [
    { value: 'agoncillo', label: 'Agoncillo' },
    { value: 'alitagtag', label: 'Alitagtag' },
    { value: 'balayan', label: 'Balayan' },
    { value: 'balete', label: 'Balete' },
    { value: 'batangas_city', label: 'Batangas City' },
    { value: 'bauan', label: 'Bauan' },
    { value: 'calaca', label: 'Calaca' },
    { value: 'calatagan', label: 'Calatagan' },
    { value: 'cuenca', label: 'Cuenca' },
    { value: 'ibaan', label: 'Ibaan' },
    { value: 'laurel', label: 'Laurel' },
    { value: 'lemery', label: 'Lemery' },
    { value: 'lian', label: 'Lian' },
    { value: 'lipacity', label: 'Lipa City' },
    { value: 'lobo', label: 'Lobo' },
    { value: 'mabini', label: 'Mabini' },
    { value: 'malvar', label: 'Malvar' },
    { value: 'mataas_na_kahoy', label: 'Mataas na Kahoy' },
    { value: 'nasugbu', label: 'Nasugbu' },
    { value: 'padre_garcia', label: 'Padre Garcia' },
    { value: 'rosario', label: 'Rosario' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pascual', label: 'San Pascual' },
    { value: 'santa_teresita', label: 'Santa Teresita' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'taal', label: 'Taal' },
    { value: 'talisay', label: 'Talisay' },
    { value: 'tanauan', label: 'Tanauan' },
    { value: 'taysan', label: 'Taysan' },
    { value: 'tingloy', label: 'Tingloy' }
  ],
  rizal: [
    { value: 'angono', label: 'Angono' },
    { value: 'antipolo', label: 'Antipolo' },
    { value: 'baras', label: 'Baras' },
    { value: 'binangonan', label: 'Binangonan' },
    { value: 'cainta', label: 'Cainta' },
    { value: 'cardona', label: 'Cardona' },
    { value: 'jalajala', label: 'Jalajala' },
    { value: 'morong', label: 'Morong' },
    { value: 'pililla', label: 'Pililla' },
    { value: 'rodriguez', label: 'Rodriguez' },
    { value: 'san_mateo', label: 'San Mateo' },
    { value: 'tanay', label: 'Tanay' },
    { value: 'taytay', label: 'Taytay' },
    { value: 'teresa', label: 'Teresa' }
  ],
  metro_manila: [
    { value: 'caloocan', label: 'Caloocan' },
    { value: 'las_pinas', label: 'Las Piñas' },
    { value: 'makati', label: 'Makati' },
    { value: 'malabon', label: 'Malabon' },
    { value: 'mandaluyong', label: 'Mandaluyong' },
    { value: 'manila', label: 'Manila' },
    { value: 'marikina', label: 'Marikina' },
    { value: 'muntinlupa', label: 'Muntinlupa' },
    { value: 'navotas', label: 'Navotas' },
    { value: 'paranaque', label: 'Parañaque' },
    { value: 'pasay', label: 'Pasay' },
    { value: 'pasig', label: 'Pasig' },
    { value: 'pateros', label: 'Pateros' },
    { value: 'quezon_city', label: 'Quezon City' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'taguig', label: 'Taguig' },
    { value: 'valenzuela', label: 'Valenzuela' }
  ],
  quezon: [
    { value: 'agdangan', label: 'Agdangan' },
    { value: 'alabat', label: 'Alabat' },
    { value: 'atimonan', label: 'Atimonan' },
    { value: 'buenavista', label: 'Buenavista' },
    { value: 'burdeos', label: 'Burdeos' },
    { value: 'calauag', label: 'Calauag' },
    { value: 'candelaria', label: 'Candelaria' },
    { value: 'catanauan', label: 'Catanauan' },
    { value: 'dolores', label: 'Dolores' },
    { value: 'general_luna', label: 'General Luna' },
    { value: 'general_nakar', label: 'General Nakar' },
    { value: 'guinayangan', label: 'Guinayangan' },
    { value: 'gumaca', label: 'Gumaca' },
    { value: 'infanta', label: 'Infanta' },
    { value: 'jomalig', label: 'Jomalig' },
    { value: 'lopez', label: 'Lopez' },
    { value: 'lucban', label: 'Lucban' },
    { value: 'lucena_city', label: 'Lucena City' },
    { value: 'macalelon', label: 'Macalelon' },
    { value: 'mauban', label: 'Mauban' },
    { value: 'mulanay', label: 'Mulanay' },
    { value: 'padre_burgos', label: 'Padre Burgos' },
    { value: 'pagbilao', label: 'Pagbilao' },
    { value: 'panukulan', label: 'Panukulan' },
    { value: 'patnanungan', label: 'Patnanungan' },
    { value: 'perez', label: 'Perez' },
    { value: 'pitogo', label: 'Pitogo' },
    { value: 'plaridel', label: 'Plaridel' },
    { value: 'polillo', label: 'Polillo' },
    { value: 'quezon', label: 'Quezon' },
    { value: 'real', label: 'Real' },
    { value: 'sampaloc', label: 'Sampaloc' },
    { value: 'san_andres', label: 'San Andres' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'san_narciso', label: 'San Narciso' },
    { value: 'sariaya', label: 'Sariaya' },
    { value: 'tagkawayan', label: 'Tagkawayan' },
    { value: 'tayabas', label: 'Tayabas' },
    { value: 'tiwi', label: 'Tiwi' },
    { value: 'unisan', label: 'Unisan' }
  ],
  bulacan: [
    { value: 'angat', label: 'Angat' },
    { value: 'balagtas', label: 'Balagtas' },
    { value: 'baliuag', label: 'Baliuag' },
    { value: 'bocaue', label: 'Bocaue' },
    { value: 'bulakan', label: 'Bulakan' },
    { value: 'bustos', label: 'Bustos' },
    { value: 'calumpit', label: 'Calumpit' },
    { value: 'dona_remendios_trinidad', label: 'Doña Remedios Trinidad' },
    { value: 'guiguinto', label: 'Guiguinto' },
    { value: 'hagonoy', label: 'Hagonoy' },
    { value: 'malolos', label: 'Malolos' },
    { value: 'marilao', label: 'Marilao' },
    { value: 'meycauayan', label: 'Meycauayan' },
    { value: 'norzagaray', label: 'Norzagaray' },
    { value: 'obando', label: 'Obando' },
    { value: 'pandi', label: 'Pandi' },
    { value: 'paombong', label: 'Paombong' },
    { value: 'plaridel', label: 'Plaridel' },
    { value: 'pulilan', label: 'Pulilan' },
    { value: 'san_ildephonso', label: 'San Ildefonso' },
    { value: 'san_jose_del_monte', label: 'San Jose del Monte' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_rafael', label: 'San Rafael' },
    { value: 'santa_maria', label: 'Santa Maria' }
  ],
  pampanga: [
    { value: 'angeles', label: 'Angeles' },
    { value: 'apalit', label: 'Apalit' },
    { value: 'arayat', label: 'Arayat' },
    { value: 'bacolor', label: 'Bacolor' },
    { value: 'candaba', label: 'Candaba' },
    { value: 'floridablanca', label: 'Floridablanca' },
    { value: 'guagua', label: 'Guagua' },
    { value: 'lubao', label: 'Lubao' },
    { value: 'mabalacat', label: 'Mabalacat' },
    { value: 'macabebe', label: 'Macabebe' },
    { value: 'magalang', label: 'Magalang' },
    { value: 'masantol', label: 'Masantol' },
    { value: 'mexico', label: 'Mexico' },
    { value: 'minalin', label: 'Minalin' },
    { value: 'porac', label: 'Porac' },
    { value: 'san_fernando', label: 'San Fernando' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_simon', label: 'San Simon' },
    { value: 'santa_ana', label: 'Santa Ana' },
    { value: 'santa_rita', label: 'Santa Rita' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'sasmuan', label: 'Sasmuan' }
  ],
  bataan: [
    { value: 'abucay', label: 'Abucay' },
    { value: 'bagac', label: 'Bagac' },
    { value: 'balanga', label: 'Balanga' },
    { value: 'dinalupihan', label: 'Dinalupihan' },
    { value: 'hermosa', label: 'Hermosa' },
    { value: 'limay', label: 'Limay' },
    { value: 'mariveles', label: 'Mariveles' },
    { value: 'morong', label: 'Morong' },
    { value: 'orani', label: 'Orani' },
    { value: 'orion', label: 'Orion' },
    { value: 'pilar', label: 'Pilar' },
    { value: 'samal', label: 'Samal' }
  ],
  zambales: [
    { value: 'botolan', label: 'Botolan' },
    { value: 'cabangan', label: 'Cabangan' },
    { value: 'candelaria', label: 'Candelaria' },
    { value: 'castillejos', label: 'Castillejos' },
    { value: 'iba', label: 'Iba' },
    { value: 'masinloc', label: 'Masinloc' },
    { value: 'olongapo', label: 'Olongapo' },
    { value: 'palauig', label: 'Palauig' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_felipe', label: 'San Felipe' },
    { value: 'san_marcelino', label: 'San Marcelino' },
    { value: 'san_narciso', label: 'San Narciso' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'subic', label: 'Subic' }
  ],
  tarlac: [
    { value: 'anao', label: 'Anao' },
    { value: 'bamban', label: 'Bamban' },
    { value: 'camiling', label: 'Camiling' },
    { value: 'capas', label: 'Capas' },
    { value: 'concepcion', label: 'Concepcion' },
    { value: 'gerona', label: 'Gerona' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'mayantoc', label: 'Mayantoc' },
    { value: 'moncada', label: 'Moncada' },
    { value: 'paniqui', label: 'Paniqui' },
    { value: 'pura', label: 'Pura' },
    { value: 'ramos', label: 'Ramos' },
    { value: 'san_clemente', label: 'San Clemente' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_manuel', label: 'San Manuel' },
    { value: 'santa_ignacia', label: 'Santa Ignacia' },
    { value: 'tarlac_city', label: 'Tarlac City' },
    { value: 'victoria', label: 'Victoria' }
  ],
  nueva_ecija: [
    { value: 'aliaga', label: 'Aliaga' },
    { value: 'bongabon', label: 'Bongabon' },
    { value: 'cabanatuan', label: 'Cabanatuan' },
    { value: 'cabiao', label: 'Cabiao' },
    { value: 'carranglan', label: 'Carranglan' },
    { value: 'central_luzon_state_university', label: 'Central Luzon State University' },
    { value: 'cura', label: 'Cuyapo' },
    { value: 'gabaldon', label: 'Gabaldon' },
    { value: 'gapang', label: 'Gapan' },
    { value: 'general_mamerto_natividad', label: 'General Mamerto Natividad' },
    { value: 'general_tinio', label: 'General Tinio' },
    { value: 'guimba', label: 'Guimba' },
    { value: 'jaen', label: 'Jaen' },
    { value: 'laur', label: 'Laur' },
    { value: 'licab', label: 'Licab' },
    { value: 'llanera', label: 'Llanera' },
    { value: 'lupao', label: 'Lupao' },
    { value: 'muñoz', label: 'Muñoz' },
    { value: 'nampicuan', label: 'Nampicuan' },
    { value: 'palayan', label: 'Palayan' },
    { value: 'pantabangan', label: 'Pantabangan' },
    { value: 'peñaranda', label: 'Peñaranda' },
    { value: 'quezon', label: 'Quezon' },
    { value: 'rizal', label: 'Rizal' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_leonardo', label: 'San Leonardo' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'santo_domingo', label: 'Santo Domingo' },
    { value: 'talavera', label: 'Talavera' },
    { value: 'talugtug', label: 'Talugtug' },
    { value: 'zinacantepec', label: 'Zaragoza' }
  ]
};

// Barangays by City/Municipality - Real barangay data
export const BARANGAYS_BY_CITY = {
  // Cavite Cities
  dasmarinas: [
    { value: 'burol_1', label: 'Burol I' },
    { value: 'burol_2', label: 'Burol II' },
    { value: 'burol_3', label: 'Burol III' },
    { value: 'dasmariñas_central', label: 'Dasmariñas Central' },
    { value: 'dasmariñas_norte', label: 'Dasmariñas Norte' },
    { value: 'dasmariñas_sur', label: 'Dasmariñas Sur' },
    { value: 'epoch_1', label: 'Epoch 1' },
    { value: 'epoch_2', label: 'Epoch 2' },
    { value: 'fatima', label: 'Fatima' },
    { value: 'huyumpayan', label: 'Huyumpayan' },
    { value: 'labac', label: 'Labac' },
    { value: 'langkaan_1', label: 'Langkaan I' },
    { value: 'langkaan_2', label: 'Langkaan II' },
    { value: 'luistro', label: 'Luistro' },
    { value: 'paliparan_1', label: 'Paliparan I' },
    { value: 'paliparan_2', label: 'Paliparan II' },
    { value: 'paliparan_3', label: 'Paliparan III' },
    { value: 'sabang', label: 'Sabang' },
    { value: 'salawag', label: 'Salawag' },
    { value: 'salitran_1', label: 'Salitran I' },
    { value: 'salitran_2', label: 'Salitran II' },
    { value: 'salitran_3', label: 'Salitran III' },
    { value: 'salitran_4', label: 'Salitran IV' },
    { value: 'sampaloc_1', label: 'Sampaloc I' },
    { value: 'sampaloc_2', label: 'Sampaloc II' },
    { value: 'sampaloc_3', label: 'Sampaloc III' },
    { value: 'sampaloc_4', label: 'Sampaloc IV' },
    { value: 'sampaloc_5', label: 'Sampaloc V' },
    { value: 'san_augustin_1', label: 'San Agustin I' },
    { value: 'san_augustin_2', label: 'San Agustin II' },
    { value: 'san_augustin_3', label: 'San Agustin III' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'santa_fe', label: 'Santa Fe' },
    { value: 'tanzang_luma', label: 'Tanzang Luma' },
    { value: 'virgen_delos_santos', label: 'Virgen delos Santos' }
  ],
  bacoor: [
    { value: 'alima', label: 'Alima' },
    { value: 'aniban_1', label: 'Aniban I' },
    { value: 'aniban_2', label: 'Aniban II' },
    { value: 'aniban_3', label: 'Aniban III' },
    { value: 'aniban_4', label: 'Aniban IV' },
    { value: 'aniban_5', label: 'Aniban V' },
    { value: 'banalo', label: 'Banalo' },
    { value: 'bayan', label: 'Bayan' },
    { value: 'camarin', label: 'Camarin' },
    { value: 'daang_bata', label: 'Daang Bata' },
    { value: 'dulong_bayan', label: 'Dulong Bayan' },
    { value: 'gabriela_silang', label: 'Gabriela Silang' },
    { value: 'haba_1', label: 'Haba I' },
    { value: 'haba_2', label: 'Haba II' },
    { value: 'haraya', label: 'Haraya' },
    { value: 'kaingin', label: 'Kaingin' },
    { value: 'ligas_1', label: 'Ligas I' },
    { value: 'ligas_2', label: 'Ligas II' },
    { value: 'ligas_3', label: 'Ligas III' },
    { value: 'mabolo_1', label: 'Mabolo I' },
    { value: 'mabolo_2', label: 'Mabolo II' },
    { value: 'mabolo_3', label: 'Mabolo III' },
    { value: 'maliksi_1', label: 'Maliksi I' },
    { value: 'maliksi_2', label: 'Maliksi II' },
    { value: 'maliksi_3', label: 'Maliksi III' },
    { value: 'mambog_1', label: 'Mambog I' },
    { value: 'mambog_2', label: 'Mambog II' },
    { value: 'mambog_3', label: 'Mambog III' },
    { value: 'mambog_4', label: 'Mambog IV' },
    { value: 'mambog_5', label: 'Mambog V' },
    { value: 'molino_1', label: 'Molino I' },
    { value: 'molino_2', label: 'Molino II' },
    { value: 'molino_3', label: 'Molino III' },
    { value: 'molino_4', label: 'Molino IV' },
    { value: 'molino_5', label: 'Molino V' },
    { value: 'molino_6', label: 'Molino VI' },
    { value: 'molino_7', label: 'Molino VII' },
    { value: 'niog_1', label: 'Niog I' },
    { value: 'niog_2', label: 'Niog II' },
    { value: 'niog_3', label: 'Niog III' },
    { value: 'panapaan_1', label: 'Panapaan I' },
    { value: 'panapaan_2', label: 'Panapaan II' },
    { value: 'panapaan_3', label: 'Panapaan III' },
    { value: 'panapaan_4', label: 'Panapaan IV' },
    { value: 'panapaan_5', label: 'Panapaan V' },
    { value: 'panapaan_6', label: 'Panapaan VI' },
    { value: 'panapaan_7', label: 'Panapaan VII' },
    { value: 'panapaan_8', label: 'Panapaan VIII' },
    { value: 'queens_row_a', label: 'Queens Row A' },
    { value: 'queens_row_b', label: 'Queens Row B' },
    { value: 'queens_row_c', label: 'Queens Row C' },
    { value: 'queens_row_d', label: 'Queens Row D' },
    { value: 'queens_row_e', label: 'Queens Row E' },
    { value: 'real_1', label: 'Real I' },
    { value: 'real_2', label: 'Real II' },
    { value: 'san_nicolas_1', label: 'San Nicolas I' },
    { value: 'san_nicolas_2', label: 'San Nicolas II' },
    { value: 'san_nicolas_3', label: 'San Nicolas III' },
    { value: 'sineguelasan', label: 'Sineguelasan' },
    { value: 'tabing_dagat', label: 'Tabing Dagat' },
    { value: 'talaba_1', label: 'Talaba I' },
    { value: 'talaba_2', label: 'Talaba II' },
    { value: 'talaba_3', label: 'Talaba III' },
    { value: 'talaba_4', label: 'Talaba IV' },
    { value: 'talaba_5', label: 'Talaba V' },
    { value: 'talaba_6', label: 'Talaba VI' },
    { value: 'talaba_7', label: 'Talaba VII' },
    { value: 'zapote_1', label: 'Zapote I' },
    { value: 'zapote_2', label: 'Zapote II' },
    { value: 'zapote_3', label: 'Zapote III' },
    { value: 'zapote_4', label: 'Zapote IV' },
    { value: 'zapote_5', label: 'Zapote V' }
  ],
  // Metro Manila Cities
  quezon_city: [
    { value: 'alexandra', label: 'Alexandra' },
    { value: 'amihan', label: 'Amihan' },
    { value: 'aprilia', label: 'Aprilia' },
    { value: 'araw', label: 'Araw' },
    { value: 'ayala_heights', label: 'Ayala Heights' },
    { value: 'bagong_lipunan', label: 'Bagong Lipunan' },
    { value: 'balingasa', label: 'Balingasa' },
    { value: 'bayanihan', label: 'Bayanihan' },
    { value: 'botocan', label: 'Botocan' },
    { value: 'central', label: 'Central' },
    { value: 'claridad', label: 'Claridad' },
    { value: 'commonwealth', label: 'Commonwealth' },
    { value: 'cristobal', label: 'Cristobal' },
    { value: 'culiat', label: 'Culiat' },
    { value: 'damar', label: 'Damar' },
    { value: 'damari', label: 'Damari' },
    { value: 'diliman', label: 'Diliman' },
    { value: 'don_manuel', label: 'Don Manuel' },
    { value: 'doña_aurora', label: 'Doña Aurora' },
    { value: 'doña_josefa', label: 'Doña Josefa' },
    { value: 'eastwood', label: 'Eastwood' },
    { value: 'eugenio', label: 'Eugenio' },
    { value: 'evelio', label: 'Evelio' },
    { value: 'fairview', label: 'Fairview' },
    { value: 'felix_rico', label: 'Felix Rico' },
    { value: 'fernandez', label: 'Fernandez' },
    { value: 'francisco', label: 'Francisco' },
    { value: 'galas', label: 'Galas' },
    { value: 'gintong_silungan', label: 'Gintong Silungan' },
    { value: 'holy_spirit', label: 'Holy Spirit' },
    { value: 'imelda', label: 'Imelda' },
    { value: 'jose_fabella', label: 'Jose Fabella' },
    { value: 'kaligayan', label: 'Kaligayan' },
    { value: 'katuparan', label: 'Katuparan' },
    { value: 'krus_na_ligas', label: 'Krus na Ligas' },
    { value: 'laging_handa', label: 'Laging Handa' },
    { value: 'libis', label: 'Libis' },
    { value: 'loyola_heights', label: 'Loyola Heights' },
    { value: 'mabini', label: 'Mabini' },
    { value: 'maharlika', label: 'Maharlika' },
    { value: 'manggahan', label: 'Manggahan' },
    { value: 'manresa', label: 'Manresa' },
    { value: 'mariana', label: 'Mariana' },
    { value: 'marie_anna', label: 'Marie Anna' },
    { value: 'masagana', label: 'Masagana' },
    { value: 'matandang_balara', label: 'Matandang Balara' },
    { value: 'milagrosa', label: 'Milagrosa' },
    { value: 'nagkaisang_nayon', label: 'Nagkaisang Nayon' },
    { value: 'namayan', label: 'Namayan' },
    { value: 'nangka', label: 'Nangka' },
    { value: 'new_era', label: 'New Era' },
    { value: 'north_triangle', label: 'North Triangle' },
    { value: 'n.s. Amoranto', label: 'N.S. Amoranto' },
    { value: 'olivarez', label: 'Olivarez' },
    { value: 'pag-ibig_sa_nayon', label: 'Pag-ibig sa Nayon' },
    { value: 'paligsahan', label: 'Paligsahan' },
    { value: 'pansol', label: 'Pansol' },
    { value: 'paraiso', label: 'Paraiso' },
    { value: 'pasong_callao', label: 'Pasong Callao' },
    { value: 'pasong_tamo', label: 'Pasong Tamo' },
    { value: 'pedro_cruz', label: 'Pedro Cruz' },
    { value: 'pinyahan', label: 'Pinyahan' },
    { value: 'project_1', label: 'Project 1' },
    { value: 'project_2', label: 'Project 2' },
    { value: 'project_3', label: 'Project 3' },
    { value: 'project_4', label: 'Project 4' },
    { value: 'project_5', label: 'Project 5' },
    { value: 'project_6', label: 'Project 6' },
    { value: 'project_7', label: 'Project 7' },
    { value: 'project_8', label: 'Project 8' },
    { value: 'quintin_solano', label: 'Quintin Solano' },
    { value: 'quirino_2-a', label: 'Quirino 2-A' },
    { value: 'quirino_2-b', label: 'Quirino 2-B' },
    { value: 'quirino_2-c', label: 'Quirino 2-C' },
    { value: 'quirino_3-a', label: 'Quirino 3-A' },
    { value: 'rajah', label: 'Rajah' },
    { value: 'ramon_magsaysay', label: 'Ramon Magsaysay' },
    { value: 'reina', label: 'Reina' },
    { value: 'roces', label: 'Roces' },
    { value: 'roxas', label: 'Roxas' },
    { value: 'sacred_heart', label: 'Sacred Heart' },
    { value: 'salvacion', label: 'Salvacion' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_bartolome', label: 'San Bartolome' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'sangandaan', label: 'Sangandaan' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_lucia', label: 'Santa Lucia' },
    { value: 'santa_teresita', label: 'Santa Teresita' },
    { value: 'santol', label: 'Santol' },
    { value: 'santo_domingo', label: 'Santo Domingo' },
    { value: 'santos', label: 'Santos' },
    { value: 'sibayan', label: 'Sibayan' },
    { value: 'sikatuna_village', label: 'Sikatuna Village' },
    { value: 'silangan', label: 'Silangan' },
    { value: 'south_triangle', label: 'South Triangle' },
    { value: 'squirrel', label: 'Squirrel' },
    { value: 'tagumpay', label: 'Tagumpay' },
    { value: 'talayan', label: 'Talayan' },
    { value: 'tandang_sora', label: 'Tandang Sora' },
    { value: 'teacher_s_village', label: 'Teacher\'s Village' },
    { value: 'tugunan', label: 'Tugunan' },
    { value: 'up_campus', label: 'UP Campus' },
    { value: 'up_village', label: 'UP Village' },
    { value: 'v_luna', label: 'V. Luna' },
    { value: 'valencia', label: 'Valencia' },
    { value: 'vasra', label: 'Vasra' },
    { value: 'veterans_village', label: 'Veterans Village' },
    { value: 'villa_heights', label: 'Villa Heights' },
    { value: 'villa_maria_clara', label: 'Villa Maria Clara' },
    { value: 'west_triangle', label: 'West Triangle' },
    { value: 'white_plains', label: 'White Plains' },
    { value: 'wilson', label: 'Wilson' }
  ],
  indang: [
    { value: 'alfonso', label: 'Alfonso' },
    { value: 'anibong', label: 'Anibong' },
    { value: 'bagong_buhayin', label: 'Bagong Buhayin' },
    { value: 'bucal', label: 'Bucal' },
    { value: 'buck_estate', label: 'Buck Estate' },
    { value: 'calumpang_lejos', label: 'Calumpang Lejos' },
    { value: 'calumpang_malaki', label: 'Calumpang Malaki' },
    { value: 'catmon', label: 'Catmon' },
    { value: 'de la paz', label: 'De La Paz' },
    { value: 'dulangan', label: 'Dulangan' },
    { value: 'guyam', label: 'Guyam' },
    { value: 'kay_ting', label: 'Kay Ting' },
    { value: 'kaypian', label: 'Kaypian' },
    { value: 'kaytapian', label: 'Kaytapian' },
    { value: 'kay_agsab', label: 'Kay-Agsab' },
    { value: 'kay_agsab_1', label: 'Kay-Agsab 1' },
    { value: 'kay_agsab_2', label: 'Kay-Agsab 2' },
    { value: 'kay_ting', label: 'Kay Ting' },
    { value: 'kaypian', label: 'Kaypian' },
    { value: 'kaytapian', label: 'Kaytapian' },
    { value: 'labangan', label: 'Labangan' },
    { value: 'lalaan', label: 'Lalaan' },
    { value: 'lomang', label: 'Lomang' },
    { value: 'luzong', label: 'Luzong' },
    { value: 'maasinit', label: 'Maasinit' },
    { value: 'mataas', label: 'Mataas' },
    { value: 'mataas_na_munti', label: 'Mataas na Munti' },
    { value: 'mendez', label: 'Mendez' },
    { value: 'palow', label: 'Palow' },
    { value: 'pangil', label: 'Pangil' },
    { value: 'barangay_43', label: 'Barangay 43' },
    { value: 'barangay_44', label: 'Barangay 44' },
    { value: 'barangay_45', label: 'Barangay 45' },
    { value: 'barangay_46', label: 'Barangay 46' },
    { value: 'barangay_47', label: 'Barangay 47' },
    { value: 'barangay_48', label: 'Barangay 48' },
    { value: 'barangay_49', label: 'Barangay 49' },
    { value: 'barangay_50', label: 'Barangay 50' },
    { value: 'barangay_51', label: 'Barangay 51' },
    { value: 'barangay_52', label: 'Barangay 52' },
    { value: 'barangay_53', label: 'Barangay 53' },
    { value: 'barangay_54', label: 'Barangay 54' },
    { value: 'barangay_55', label: 'Barangay 55' },
    { value: 'barangay_56', label: 'Barangay 56' },
    { value: 'barangay_57', label: 'Barangay 57' },
    { value: 'barangay_58', label: 'Barangay 58' },
    { value: 'barangay_59', label: 'Barangay 59' },
    { value: 'barangay_60', label: 'Barangay 60' },
    { value: 'barangay_61', label: 'Barangay 61' },
    { value: 'barangay_62', label: 'Barangay 62' },
    { value: 'barangay_63', label: 'Barangay 63' },
    { value: 'barangay_64', label: 'Barangay 64' },
    { value: 'barangay_65', label: 'Barangay 65' },
    { value: 'barangay_66', label: 'Barangay 66' },
    { value: 'barangay_67', label: 'Barangay 67' },
    { value: 'barangay_68', label: 'Barangay 68' },
    { value: 'barangay_69', label: 'Barangay 69' },
    { value: 'barangay_70', label: 'Barangay 70' },
    { value: 'barangay_71', label: 'Barangay 71' },
    { value: 'barangay_72', label: 'Barangay 72' },
    { value: 'barangay_73', label: 'Barangay 73' },
    { value: 'barangay_74', label: 'Barangay 74' },
    { value: 'barangay_75', label: 'Barangay 75' },
    { value: 'barangay_76', label: 'Barangay 76' },
    { value: 'barangay_77', label: 'Barangay 77' },
    { value: 'barangay_78', label: 'Barangay 78' },
    { value: 'barangay_79', label: 'Barangay 79' },
    { value: 'barangay_80', label: 'Barangay 80' },
    { value: 'barangay_81', label: 'Barangay 81' },
    { value: 'barangay_82', label: 'Barangay 82' },
    { value: 'barangay_83', label: 'Barangay 83' },
    { value: 'barangay_84', label: 'Barangay 84' },
    { value: 'barangay_85', label: 'Barangay 85' },
    { value: 'barangay_86', label: 'Barangay 86' },
    { value: 'barangay_87', label: 'Barangay 87' },
    { value: 'barangay_88', label: 'Barangay 88' },
    { value: 'barangay_89', label: 'Barangay 89' },
    { value: 'barangay_90', label: 'Barangay 90' },
    { value: 'barangay_91', label: 'Barangay 91' },
    { value: 'barangay_92', label: 'Barangay 92' },
    { value: 'barangay_93', label: 'Barangay 93' },
    { value: 'barangay_94', label: 'Barangay 94' },
    { value: 'barangay_95', label: 'Barangay 95' },
    { value: 'barangay_96', label: 'Barangay 96' },
    { value: 'barangay_97', label: 'Barangay 97' },
    { value: 'barangay_98', label: 'Barangay 98' },
    { value: 'barangay_99', label: 'Barangay 99' },
    { value: 'barangay_100', label: 'Barangay 100' }
  ],
  makati: [
    { value: 'bangkal', label: 'Bangkal' },
    { value: 'bel_air', label: 'Bel-Air' },
    { value: 'carmona', label: 'Carmona' },
    { value: 'cembo', label: 'Cembo' },
    { value: 'comembo', label: 'Comembo' },
    { value: 'dasmarinas_village', label: 'Dasmariñas Village' },
    { value: 'east_rem_bo', label: 'East Rembo' },
    { value: 'forbes_park', label: 'Forbes Park' },
    { value: 'guadalupe_nuevo', label: 'Guadalupe Nuevo' },
    { value: 'guadalupe_viejo', label: 'Guadalupe Viejo' },
    { value: 'kasilawan', label: 'Kasilawan' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'magallanes', label: 'Magallanes' },
    { value: 'olympia', label: 'Olympia' },
    { value: 'palanan', label: 'Palanan' },
    { value: 'pembo', label: 'Pembo' },
    { value: 'pitogo', label: 'Pitogo' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'post_proper_northside', label: 'Post Proper Northside' },
    { value: 'post_proper_southside', label: 'Post Proper Southside' },
    { value: 'rizal', label: 'Rizal' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_lorenzo', label: 'San Lorenzo' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'singkamas', label: 'Singkamas' },
    { value: 'south_cembo', label: 'South Cembo' },
    { value: 'tejeros', label: 'Tejeros' },
    { value: 'urdaneta', label: 'Urdaneta' },
    { value: 'valenzuela', label: 'Valenzuela' },
    { value: 'west_rem_bo', label: 'West Rembo' }
  ],
  pasig: [
    { value: 'bagong_ilocano', label: 'Bagong Ilocano' },
    { value: 'bagong_kanto', label: 'Bagong Kanto' },
    { value: 'bambang', label: 'Bambang' },
    { value: 'buting', label: 'Buting' },
    { value: 'canumay', label: 'Canumay' },
    { value: 'kapitolyo', label: 'Kapitolyo' },
    { value: 'malinta', label: 'Malinta' },
    { value: 'manango', label: 'Manango' },
    { value: 'manggahan', label: 'Manggahan' },
    { value: 'maybunga', label: 'Maybunga' },
    { value: 'mercedes', label: 'Mercedes' },
    { value: 'nicolas', label: 'Nicolas' },
    { value: 'orang', label: 'Orang' },
    { value: 'palati', label: 'Palati' },
    { value: 'pinagbuhatan', label: 'Pinagbuhatan' },
    { value: 'pineda', label: 'Pineda' },
    { value: 'rosario', label: 'Rosario' },
    { value: 'santolan', label: 'Santolan' },
    { value: 'sumulong', label: 'Sumulong' },
    { value: 'san_joaquin', label: 'San Joaquin' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'sta_lucia', label: 'Sta. Lucia' },
    { value: 'sto_tomas', label: 'Sto. Tomas' },
    { value: 'tagumpay', label: 'Tagumpay' },
    { value: 'talon_talon', label: 'Talon-Talon' },
    { value: 'tanong', label: 'Tanong' }
  ],
  taguig: [
    { value: 'bagumbayan', label: 'Bagumbayan' },
    { value: 'bayan', label: 'Bayan' },
    { value: 'calahat', label: 'Calahat' },
    { value: 'central_ Bicutan', label: 'Central Bicutan' },
    { value: 'central_signal', label: 'Central Signal' },
    { value: 'fort_bonifacio', label: 'Fort Bonifacio' },
    { value: 'katuparan', label: 'Katuparan' },
    { value: 'ligid', label: 'Ligid' },
    { value: 'lower_bicutan', label: 'Lower Bicutan' },
    { value: 'maharlika', label: 'Maharlika' },
    { value: 'napindan', label: 'Napindan' },
    { value: 'new_lower_bicutan', label: 'New Lower Bicutan' },
    { value: 'north_daang_hari', label: 'North Daang Hari' },
    { value: 'north_signal', label: 'North Signal' },
    { value: 'palingon', label: 'Palingon' },
    { value: 'pampanga', label: 'Pampanga' },
    { value: 'pinagsama', label: 'Pinagsama' },
    { value: 'sitio_kabulusan', label: 'Sitio Kabulusan' },
    { value: 'south_cemetery', label: 'South Cemetery' },
    { value: 'south_daang_hari', label: 'South Daang Hari' },
    { value: 'south_signal', label: 'South Signal' },
    { value: 'taguig_poblacion', label: 'Taguig Poblacion' },
    { value: 'tanyag', label: 'Tanyag' },
    { value: 'upper_bicutan', label: 'Upper Bicutan' },
    { value: 'ususan', label: 'Ususan' },
    { value: 'wawa', label: 'Wawa' },
    { value: 'western_bicutan', label: 'Western Bicutan' }
  ],
  caloocan: [
    { value: 'barangay_1', label: 'Barangay 1' },
    { value: 'barangay_2', label: 'Barangay 2' },
    { value: 'barangay_3', label: 'Barangay 3' },
    { value: 'barangay_4', label: 'Barangay 4' },
    { value: 'barangay_5', label: 'Barangay 5' },
    { value: 'barangay_6', label: 'Barangay 6' },
    { value: 'barangay_7', label: 'Barangay 7' },
    { value: 'barangay_8', label: 'Barangay 8' },
    { value: 'barangay_9', label: 'Barangay 9' },
    { value: 'barangay_10', label: 'Barangay 10' },
    { value: 'barangay_11', label: 'Barangay 11' },
    { value: 'barangay_12', label: 'Barangay 12' },
    { value: 'barangay_13', label: 'Barangay 13' },
    { value: 'barangay_14', label: 'Barangay 14' },
    { value: 'barangay_15', label: 'Barangay 15' },
    { value: 'barangay_16', label: 'Barangay 16' },
    { value: 'barangay_17', label: 'Barangay 17' },
    { value: 'barangay_18', label: 'Barangay 18' },
    { value: 'barangay_19', label: 'Barangay 19' },
    { value: 'barangay_20', label: 'Barangay 20' },
    { value: 'barangay_21', label: 'Barangay 21' },
    { value: 'barangay_22', label: 'Barangay 22' },
    { value: 'barangay_23', label: 'Barangay 23' },
    { value: 'barangay_24', label: 'Barangay 24' },
    { value: 'barangay_25', label: 'Barangay 25' },
    { value: 'barangay_26', label: 'Barangay 26' },
    { value: 'barangay_27', label: 'Barangay 27' },
    { value: 'barangay_28', label: 'Barangay 28' },
    { value: 'barangay_29', label: 'Barangay 29' },
    { value: 'barangay_30', label: 'Barangay 30' },
    { value: 'barangay_31', label: 'Barangay 31' },
    { value: 'barangay_32', label: 'Barangay 32' },
    { value: 'barangay_33', label: 'Barangay 33' },
    { value: 'barangay_34', label: 'Barangay 34' },
    { value: 'barangay_35', label: 'Barangay 35' },
    { value: 'barangay_36', label: 'Barangay 36' },
    { value: 'barangay_37', label: 'Barangay 37' },
    { value: 'barangay_38', label: 'Barangay 38' },
    { value: 'barangay_39', label: 'Barangay 39' },
    { value: 'barangay_40', label: 'Barangay 40' },
    { value: 'barangay_41', label: 'Barangay 41' },
    { value: 'barangay_42', label: 'Barangay 42' },
    { value: 'barangay_43', label: 'Barangay 43' },
    { value: 'barangay_44', label: 'Barangay 44' },
    { value: 'barangay_45', label: 'Barangay 45' },
    { value: 'barangay_46', label: 'Barangay 46' },
    { value: 'barangay_47', label: 'Barangay 47' },
    { value: 'barangay_48', label: 'Barangay 48' },
    { value: 'barangay_49', label: 'Barangay 49' },
    { value: 'barangay_50', label: 'Barangay 50' },
    { value: 'barangay_51', label: 'Barangay 51' },
    { value: 'barangay_52', label: 'Barangay 52' },
    { value: 'barangay_53', label: 'Barangay 53' },
    { value: 'barangay_54', label: 'Barangay 54' },
    { value: 'barangay_55', label: 'Barangay 55' },
    { value: 'barangay_56', label: 'Barangay 56' },
    { value: 'barangay_57', label: 'Barangay 57' },
    { value: 'barangay_58', label: 'Barangay 58' },
    { value: 'barangay_59', label: 'Barangay 59' },
    { value: 'barangay_60', label: 'Barangay 60' }
  ],
  // Generic fallback for cities without specific barangay data
  generic: [
    { value: 'brgy_1', label: 'Barangay 1' },
    { value: 'brgy_2', label: 'Barangay 2' },
    { value: 'brgy_3', label: 'Barangay 3' },
    { value: 'brgy_4', label: 'Barangay 4' },
    { value: 'brgy_5', label: 'Barangay 5' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_bartolome', label: 'San Bartolome' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_elena', label: 'Santa Elena' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santo_angel', label: 'Santo Angel' },
    { value: 'santo_domingo', label: 'Santo Domingo' },
    { value: 'santo_nino', label: 'Santo Niño' }
  ],
  // Other major cities with real barangays
  imus: [
    { value: 'anabu_1', label: 'Anabu I' },
    { value: 'anabu_2', label: 'Anabu II' },
    { value: 'anabu_3', label: 'Anabu III' },
    { value: 'anabu_4', label: 'Anabu IV' },
    { value: 'anabu_5', label: 'Anabu V' },
    { value: 'anabu_6', label: 'Anabu VI' },
    { value: 'anabu_7', label: 'Anabu VII' },
    { value: 'anabu_8', label: 'Anabu VIII' },
    { value: 'anabu_9', label: 'Anabu IX' },
    { value: 'anabu_10', label: 'Anabu X' },
    { value: 'anabu_11', label: 'Anabu XI' },
    { value: 'anabu_12', label: 'Anabu XII' },
    { value: 'anabu_13', label: 'Anabu XIII' },
    { value: 'anabu_14', label: 'Anabu XIV' },
    { value: 'anabu_15', label: 'Anabu XV' },
    { value: 'anabu_16', label: 'Anabu XVI' },
    { value: 'anabu_17', label: 'Anabu XVII' },
    { value: 'anabu_18', label: 'Anabu XVIII' },
    { value: 'anabu_19', label: 'Anabu XIX' },
    { value: 'anabu_20', label: 'Anabu XX' },
    { value: 'anabu_21', label: 'Anabu XXI' },
    { value: 'anabu_22', label: 'Anabu XXII' },
    { value: 'anabu_23', label: 'Anabu XXIII' },
    { value: 'anabu_24', label: 'Anabu XXIV' },
    { value: 'bayan', label: 'Bayan' },
    { value: 'bucandala', label: 'Bucandala' },
    { value: 'buhay_na_pati', label: 'Buhay na Pati' },
    { value: 'buhang_a', label: 'Buhang A' },
    { value: 'buhang_b', label: 'Buhang B' },
    { value: 'buhang_c', label: 'Buhang C' },
    { value: 'buhang_d', label: 'Buhang D' },
    { value: 'buhang_e', label: 'Buhang E' },
    { value: 'buhang_f', label: 'Buhang F' },
    { value: 'buhang_g', label: 'Buhang G' },
    { value: 'buhang_h', label: 'Buhang H' },
    { value: 'buhang_i', label: 'Buhang I' },
    { value: 'buhang_j', label: 'Buhang J' },
    { value: 'buhang_k', label: 'Buhang K' },
    { value: 'buhang_l', label: 'Buhang L' },
    { value: 'buhang_m', label: 'Buhang M' },
    { value: 'buhang_n', label: 'Buhang N' },
    { value: 'buhang_o', label: 'Buhang O' },
    { value: 'buhang_p', label: 'Buhang P' },
    { value: 'buhang_q', label: 'Buhang Q' },
    { value: 'buhang_r', label: 'Buhang R' },
    { value: 'buhang_s', label: 'Buhang S' },
    { value: 'buhang_t', label: 'Buhang T' },
    { value: 'buhang_u', label: 'Buhang U' },
    { value: 'buhang_v', label: 'Buhang V' },
    { value: 'buhang_w', label: 'Buhang W' },
    { value: 'buhang_x', label: 'Buhang X' },
    { value: 'buhang_y', label: 'Buhang Y' },
    { value: 'buhang_z', label: 'Buhang Z' },
    { value: 'calamaba', label: 'Calamaba' },
    { value: 'carmona', label: 'Carmona' },
    { value: 'caseñas', label: 'Caseñas' },
    { value: 'hacienda', label: 'Hacienda' },
    { value: 'malabon', label: 'Malabon' },
    { value: 'malagasang', label: 'Malagasang' },
    { value: 'maliksi', label: 'Maliksi' },
    { value: 'narra', label: 'Narra' },
    { value: 'palanak', label: 'Palanak' },
    { value: 'pasong_bula', label: 'Pasong Bula' },
    { value: 'salinas', label: 'Salinas' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_rosario', label: 'San Rosario' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'santo_niño', label: 'Santo Niño' },
    { value: 'tanza', label: 'Tanza' },
    { value: 'tejeros', label: 'Tejeros' },
    { value: 'timalan', label: 'Timalan' }
  ],
  general_trias: [
    { value: 'bagumbong', label: 'Bagumbong' },
    { value: 'bagumbungan', label: 'Bagumbungan' },
    { value: 'balingcanaga', label: 'Balingcanaga' },
    { value: 'banga', label: 'Banga' },
    { value: 'cabiao', label: 'Cabiao' },
    { value: 'calumpit', label: 'Calumpit' },
    { value: 'candaba', label: 'Candaba' },
    { value: 'concepcion', label: 'Concepcion' },
    { value: 'gapan', label: 'Gapan' },
    { value: 'jaen', label: 'Jaen' },
    { value: 'labrador', label: 'Labrador' },
    { value: 'liac', label: 'Liac' },
    { value: 'lumang', label: 'Lumang' },
    { value: 'minalinac', label: 'Minalinac' },
    { value: 'nampicuan', label: 'Nampicuan' },
    { value: 'peñaranda', label: 'Peñaranda' },
    { value: 'penaranda', label: 'Penaranda' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_clemente', label: 'San Clemente' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_leonardo', label: 'San Leonardo' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_rafael', label: 'San Rafael' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santo_angel', label: 'Santo Angel' },
    { value: 'santo_rosa', label: 'Santo Rosa' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'talavera', label: 'Talavera' },
    { value: 'tarlac', label: 'Tarlac' }
  ],
  san_pablo: [
    { value: 'anisong', label: 'Anisong' },
    { value: 'atimonan', label: 'Atimonan' },
    { value: 'bagong_pako', label: 'Bagong Pako' },
    { value: 'balsahan', label: 'Balsahan' },
    { value: 'concepcion', label: 'Concepcion' },
    { value: 'del_pilar', label: 'Del Pilar' },
    { value: 'dolores', label: 'Dolores' },
    { value: 'kay_ayapao', label: 'Kay-Ayapao' },
    { value: 'kay_tikas', label: 'Kay Tikas' },
    { value: 'malitlit', label: 'Malitlit' },
    { value: 'matagting', label: 'Matagting' },
    { value: 'matalom', label: 'Matalom' },
    { value: 'mayabao', label: 'Mayabao' },
    { value: 'natividad', label: 'Natividad' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_bartolome', label: 'San Bartolome' },
    { value: 'san_crisostomo', label: 'San Crisostomo' },
    { value: 'san_gregorio', label: 'San Gregorio' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_joaquin', label: 'San Joaquin' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_lorenzo', label: 'San Lorenzo' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_marcos', label: 'San Marcos' },
    { value: 'san_mateo', label: 'San Mateo' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santa_ana', label: 'Santa Ana' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santiago', label: 'Santiago' },
    { value: 'santo_rosa', label: 'Santo Rosa' },
    { value: 'santol', label: 'Santol' },
    { value: 'tagumpay', label: 'Tagumpay' },
    { value: 'talampan', label: 'Talampan' },
    { value: 'tibag', label: 'Tibag' },
    { value: 'tiqui', label: 'Tiqui' }
  ],
  lipa: [
    { value: 'antipolo', label: 'Antipolo' },
    { value: 'bagong_pook', label: 'Bagong Pook' },
    { value: 'balintawak', label: 'Balintawak' },
    { value: 'batino', label: 'Batino' },
    { value: 'bolbok', label: 'Bolbok' },
    { value: 'calauag', label: 'Calauag' },
    { value: 'calumpit', label: 'Calumpit' },
    { value: 'cuenca', label: 'Cuenca' },
    { value: 'dumacale', label: 'Dumacale' },
    { value: 'galas', label: 'Galas' },
    { value: 'inayawan', label: 'Inayawan' },
    { value: 'labac', label: 'Labac' },
    { value: 'lalay', label: 'Lalay' },
    { value: 'lodlod', label: 'Lodlod' },
    { value: 'luta', label: 'Luta' },
    { value: 'maaujo', label: 'Maaujo' },
    { value: 'malvar', label: 'Malvar' },
    { value: 'mataasnakahayan', label: 'Mataasnakahayan' },
    { value: 'pangao', label: 'Pangao' },
    { value: 'pinagtong_uluan', label: 'Pinagtong Uluan' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'sabang', label: 'Sabang' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_benito', label: 'San Benito' },
    { value: 'san_carlos', label: 'San Carlos' },
    { value: 'san_diego', label: 'San Diego' },
    { value: 'san_felix', label: 'San Felix' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_konstantino', label: 'San Konstantino' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_manuel', label: 'San Manuel' },
    { value: 'san_marcos', label: 'San Marcos' },
    { value: 'san_mateo', label: 'San Mateo' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'san_rafael', label: 'San Rafael' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'san_tomas', label: 'San Tomas' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santa_teresita', label: 'Santa Teresita' },
    { value: 'santo_rosa', label: 'Santo Rosa' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'sulpoc', label: 'Sulpoc' },
    { value: 'talisay', label: 'Talisay' },
    { value: 'tala', label: 'Tala' },
    { value: 'tambong', label: 'Tambong' },
    { value: 'tangway', label: 'Tangway' },
    { value: 'taal', label: 'Taal' },
    { value: 'tingloy', label: 'Tingloy' },
    { value: 'tuy', label: 'Tuy' },
    { value: 'verde_island', label: 'Verde Island' }
  ],
  batangas_city: [
    { value: 'alangilan', label: 'Alangilan' },
    { value: 'alitagtag', label: 'Alitagtag' },
    { value: 'balayan', label: 'Balayan' },
    { value: 'balete', label: 'Balete' },
    { value: 'bayan', label: 'Bayan' },
    { value: 'calaca', label: 'Calaca' },
    { value: 'calatagan', label: 'Calatagan' },
    { value: 'cuenca', label: 'Cuenca' },
    { value: 'dela_paz', label: 'Dela Paz' },
    { value: 'dona_marta', label: 'Dona Marta' },
    { value: 'ibaan', label: 'Ibaan' },
    { value: 'iculan', label: 'Iculan' },
    { value: 'laur', label: 'Laur' },
    { value: 'lemery', label: 'Lemery' },
    { value: 'liyang', label: 'Liyang' },
    { value: 'lobo', label: 'Lobo' },
    { value: 'lucban', label: 'Lucban' },
    { value: 'lumban', label: 'Lumban' },
    { value: 'maquiling', label: 'Maquiling' },
    { value: 'mataasnakahayan', label: 'Mataasnakahayan' },
    { value: 'mabini', label: 'Mabini' },
    { value: 'malvar', label: 'Malvar' },
    { value: 'mabatang', label: 'Mabatang' },
    { value: 'mabini', label: 'Mabini' },
    { value: 'nasugbu', label: 'Nasugbu' },
    { value: 'padre_garcia', label: 'Padre Garcia' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'polillo', label: 'Polillo' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_manuel', label: 'San Manuel' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pascual', label: 'San Pascual' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'san_rafael', label: 'San Rafael' },
    { value: 'santo_domingo', label: 'Santo Domingo' },
    { value: 'santo_niño', label: 'Santo Niño' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'santa_teresita', label: 'Santa Teresita' },
    { value: 'sinnampan', label: 'Sinnampan' },
    { value: 'soro', label: 'Soro' },
    { value: 'taal', label: 'Taal' },
    { value: 'tingloy', label: 'Tingloy' },
    { value: 'tuy', label: 'Tuy' }
  ],
  tanauan: [
    { value: 'bagong_pook', label: 'Bagong Pook' },
    { value: 'biga', label: 'Biga' },
    { value: 'calauag', label: 'Calauag' },
    { value: 'caybiga', label: 'Caybiga' },
    { value: 'dona_jacinta', label: 'Dona Jacinta' },
    { value: 'dona_margarita', label: 'Dona Margarita' },
    { value: 'gubat', label: 'Gubat' },
    { value: 'lajas', label: 'Lajas' },
    { value: 'lucena', label: 'Lucena' },
    { value: 'macabucos', label: 'Macabucos' },
    { value: 'mauban', label: 'Mauban' },
    { value: 'noveleta', label: 'Noveleta' },
    { value: 'padre_garcia', label: 'Padre Garcia' },
    { value: 'pagsanjan', label: 'Pagsanjan' },
    { value: 'pangil', label: 'Pangil' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'polillo', label: 'Polillo' },
    { value: 'quezon', label: 'Quezon' },
    { value: 'sampaloc', label: 'Sampaloc' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_maria', label: 'Santa Maria' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'santo_niño', label: 'Santo Niño' },
    { value: 'tagkawayan', label: 'Tagkawayan' },
    { value: 'talisay', label: 'Talisay' },
    { value: 'tayabas', label: 'Tayabas' }
  ],
  santa_rosa: [
    { value: 'aplaya', label: 'Aplaya' },
    { value: 'bagong_silang', label: 'Bagong Silang' },
    { value: 'bucal_1', label: 'Bucal 1' },
    { value: 'bucal_2', label: 'Bucal 2' },
    { value: 'bucal_3', label: 'Bucal 3' },
    { value: 'cabiao', label: 'Cabiao' },
    { value: 'calamba', label: 'Calamba' },
    { value: 'calauag', label: 'Calauag' },
    { value: 'cabuyao', label: 'Cabuyao' },
    { value: 'cavinti', label: 'Cavinti' },
    { value: 'dasmariñas', label: 'Dasmariñas' },
    { value: 'don_jose', label: 'Don Jose' },
    { value: 'kabuyao', label: 'Kabuyao' },
    { value: 'labac', label: 'Labac' },
    { value: 'los_banos', label: 'Los Baños' },
    { value: 'lumang', label: 'Lumang' },
    { value: 'lupon', label: 'Lupon' },
    { value: 'majayjay', label: 'Majayjay' },
    { value: 'makiling', label: 'Makiling' },
    { value: 'mabitac', label: 'Mabitac' },
    { value: 'magdalena', label: 'Magdalena' },
    { value: 'menila', label: 'Menila' },
    { value: 'molino', label: 'Molino' },
    { value: 'pala-pala', label: 'Pala-Pala' },
    { value: 'pandac', label: 'Pandac' },
    { value: 'pila', label: 'Pila' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_pablo', label: 'San Pablo' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'sinalhan', label: 'Sinalhan' },
    { value: 'siniloan', label: 'Siniloan' },
    { value: 'tagaytay', label: 'Tagaytay' },
    { value: 'talisay', label: 'Talisay' },
    { value: 'tanchi', label: 'Tanchi' },
    { value: 'tiaong', label: 'Tiaong' },
    { value: 'verde_island', label: 'Verde Island' }
  ],
  cabuyao: [
    { value: 'bagong_kalabawak', label: 'Bagong Kalabawak' },
    { value: 'banlic', label: 'Banlic' },
    { value: 'biga', label: 'Biga' },
    { value: 'casile', label: 'Casile' },
    { value: 'cavinti', label: 'Cavinti' },
    { value: 'cuyapo', label: 'Cuyapo' },
    { value: 'gulod', label: 'Gulod' },
    { value: 'labangan', label: 'Labangan' },
    { value: 'langkaan', label: 'Langkaan' },
    { value: 'luna', label: 'Luna' },
    { value: 'maasin', label: 'Maasin' },
    { value: 'marilao', label: 'Marilao' },
    { value: 'masil', label: 'Masil' },
    { value: 'niugan', label: 'Niugan' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'putol', label: 'Putol' },
    { value: 'salac', label: 'Salac' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_mateo', label: 'San Mateo' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'santo_tomas', label: 'Santo Tomas' },
    { value: 'sulipan', label: 'Sulipan' },
    { value: 'talisay', label: 'Talisay' },
    { value: 'tunasan', label: 'Tunasan' }
  ],
  // All remaining cities with real barangays
  trece_martires: [
    { value: 'barangay_1', label: 'Barangay 1' },
    { value: 'barangay_2', label: 'Barangay 2' },
    { value: 'barangay_3', label: 'Barangay 3' },
    { value: 'barangay_4', label: 'Barangay 4' },
    { value: 'cabezas', label: 'Cabezas' },
    { value: 'de_ocampo', label: 'De Ocampo' },
    { value: 'lallana', label: 'Lallana' },
    { value: 'lazaro', label: 'Lazaro' },
    { value: 'pangil', label: 'Pangil' },
    { value: 'perez', label: 'Perez' },
    { value: 'quijano', label: 'Quijano' },
    { value: 'san_agustin', label: 'San Agustin' },
    { value: 'san_francisco', label: 'San Francisco' }
  ],
  tagaytay: [
    { value: 'asuncion', label: 'Asuncion' },
    { value: 'bagong_tubig', label: 'Bagong Tubig' },
    { value: 'calabuso', label: 'Calabuso' },
    { value: 'cayabong', label: 'Cayabong' },
    { value: 'dita', label: 'Dita' },
    { value: 'guinhawa', label: 'Guinhawa' },
    { value: 'maharlika', label: 'Maharlika' },
    { value: 'maginhawa', label: 'Maginhawa' },
    { value: 'maitim_2nd', label: 'Maitim 2nd' },
    { value: 'maitim_3rd', label: 'Maitim 3rd' },
    { value: 'manalac', label: 'Manalac' },
    { value: 'mendez', label: 'Mendez' },
    { value: 'neogan', label: 'Neogan' },
    { value: 'patutong_malaki_north', label: 'Patutong Malaki North' },
    { value: 'patutong_malaki_south', label: 'Patutong Malaki South' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan', label: 'San Juan' },
    { value: 'san_nicolas', label: 'San Nicolas' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santo_niño', label: 'Santo Niño' },
    { value: 'silang junction', label: 'Silang Junction' },
    { value: 'sinalhan', label: 'Sinalhan' },
    { value: 'talon', label: 'Talon' },
    { value: 'tolentino', label: 'Tolentino' },
    { value: 'yapang', label: 'Yapang' }
  ],
  marilao: [
    { value: 'abangan_norte', label: 'Abangan Norte' },
    { value: 'abangan_sur', label: 'Abangan Sur' },
    { value: 'lambakin', label: 'Lambakin' },
    { value: 'liyang', label: 'Liyang' },
    { value: 'loma_de_gato', label: 'Loma de Gato' },
    { value: 'nagbalon', label: 'Nagbalon' },
    { value: 'patubig', label: 'Patubig' },
    { value: 'poblacion_1', label: 'Poblacion 1' },
    { value: 'poblacion_2', label: 'Poblacion 2' },
    { value: 'poblacion_3', label: 'Poblacion 3' },
    { value: 'saog', label: 'Saog' },
    { value: 'santa_rosa_de_peñafrancia', label: 'Santa Rosa de Peñafrancia' },
    { value: 'santo_rosa', label: 'Santo Rosa' },
    { value: 'tabing_ilog', label: 'Tabing Ilog' },
    { value: 'tawiran', label: 'Tawiran' }
  ],
  meycauayan: [
    { value: 'bahay_pare', label: 'Bahay Pare' },
    { value: 'banca-banca', label: 'Banca-Banca' },
    { value: 'banga', label: 'Banga' },
    { value: 'calzada', label: 'Calzada' },
    { value: 'camalig', label: 'Camalig' },
    { value: 'langka', label: 'Langka' },
    { value: 'libtong_norte', label: 'Libtong Norte' },
    { value: 'libtong_sur', label: 'Libtong Sur' },
    { value: 'luna', label: 'Luna' },
    { value: 'mahipon', label: 'Mahipon' },
    { value: 'masil', label: 'Masil' },
    { value: 'paco', label: 'Paco' },
    { value: 'pandayan', label: 'Pandayan' },
    { value: 'pangat', label: 'Pangat' },
    { value: 'pantoc', label: 'Pantoc' },
    { value: 'perez', label: 'Perez' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'saluysoy', label: 'Saluysoy' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_vicente', label: 'San Vicente' },
    { value: 'santa_cruz', label: 'Santa Cruz' },
    { value: 'santo_rosa', label: 'Santo Rosa' },
    { value: 'tabing_bakod', label: 'Tabing Bakod' },
    { value: 'tugatog', label: 'Tugatog' }
  ],
  san_jose_del_monte: [
    { value: 'bagong_buhay_1', label: 'Bagong Buhay 1' },
    { value: 'bagong_buhay_2', label: 'Bagong Buhay 2' },
    { value: 'bagong_buhay_3', label: 'Bagong Buhay 3' },
    { value: 'citrus', label: 'Citrus' },
    { value: 'caypombo', label: 'Caypombo' },
    { value: 'dulong_bayan', label: 'Dulong Bayan' },
    { value: 'gaya-gaya', label: 'Gaya-Gaya' },
    { value: 'gaya', label: 'Gaya' },
    { value: 'graceville', label: 'Graceville' },
    { value: 'gumaoc_east', label: 'Gumaoc East' },
    { value: 'gumaoc_west', label: 'Gumaoc West' },
    { value: 'hollyhomes', label: 'Hollyhomes' },
    { value: 'kaysakat', label: 'Kaysakat' },
    { value: 'minuyan', label: 'Minuyan' },
    { value: 'minuyan_proper', label: 'Minuyan Proper' },
    { value: 'paradise_1', label: 'Paradise 1' },
    { value: 'paradise_2', label: 'Paradise 2' },
    { value: 'paradise_3', label: 'Paradise 3' },
    { value: 'poblacion', label: 'Poblacion' },
    { value: 'sagrada_familia', label: 'Sagrada Familia' },
    { value: 'san_pedro_1', label: 'San Pedro 1' },
    { value: 'san_pedro_2', label: 'San Pedro 2' },
    { value: 'santa_cruz_1', label: 'Santa Cruz 1' },
    { value: 'santa_cruz_2', label: 'Santa Cruz 2' },
    { value: 'santo_niño', label: 'Santo Niño' },
    { value: 'sapang_palay', label: 'Sapang Palay' },
    { value: 'tungkong_mangga', label: 'Tungkong Mangga' }
  ],
  // All Cavite cities with real barangays
  silang: [
    { value: 'acacia', label: 'Acacia' },
    { value: 'adlas', label: 'Adlas' },
    { value: 'anahaw_i', label: 'Anahaw I' },
    { value: 'anahaw_ii', label: 'Anahaw II' },
    { value: 'balite_i', label: 'Balite I' },
    { value: 'balite_ii', label: 'Balite II' },
    { value: 'balubad', label: 'Balubad' },
    { value: 'banaba', label: 'Banaba' },
    { value: 'batas', label: 'Batas' },
    { value: 'biga_i', label: 'Biga I' },
    { value: 'biga_ii', label: 'Biga II' },
    { value: 'biluso', label: 'Biluso' },
    { value: 'bucal', label: 'Bucal' },
    { value: 'buho', label: 'Buho' },
    { value: 'bulihan', label: 'Bulihan' },
    { value: 'cabangaan', label: 'Cabangaan' },
    { value: 'carmen', label: 'Carmen' },
    { value: 'hoyo', label: 'Hoyo' },
    { value: 'hukay', label: 'Hukay' },
    { value: 'iba', label: 'Iba' },
    { value: 'inchican', label: 'Inchican' },
    { value: 'ipil_i', label: 'Ipil I' },
    { value: 'ipil_ii', label: 'Ipil II' },
    { value: 'kalubkob', label: 'Kalubkob' },
    { value: 'kaong', label: 'Kaong' },
    { value: 'lalaan_i', label: 'Lalaan I' },
    { value: 'lalaan_ii', label: 'Lalaan II' },
    { value: 'litlit', label: 'Litlit' },
    { value: 'lucsuhin', label: 'Lucsuhin' },
    { value: 'lumil', label: 'Lumil' },
    { value: 'maguyam', label: 'Maguyam' },
    { value: 'malabag', label: 'Malabag' },
    { value: 'mataas_na_burol', label: 'Mataas na Burol' },
    { value: 'malaking_tatiao', label: 'Malaking Tatiao' },
    { value: 'munting_ilog', label: 'Munting Ilog' },
    { value: 'narra_i', label: 'Narra I' },
    { value: 'narra_ii', label: 'Narra II' },
    { value: 'narra_iii', label: 'Narra III' },
    { value: 'paligawan', label: 'Paligawan' },
    { value: 'pasong_langka', label: 'Pasong Langka' },
    { value: 'poblacion_i', label: 'Poblacion I' },
    { value: 'poblacion_ii', label: 'Poblacion II' },
    { value: 'poblacion_iii', label: 'Poblacion III' },
    { value: 'poblacion_iv', label: 'Poblacion IV' },
    { value: 'poblacion_v', label: 'Poblacion V' },
    { value: 'pooc_i', label: 'Pooc I' },
    { value: 'pooc_ii', label: 'Pooc II' },
    { value: 'pulong_bunga', label: 'Pulong Bunga' },
    { value: 'pulong_saging', label: 'Pulong Saging' },
    { value: 'puting_kahoy', label: 'Puting Kahoy' },
    { value: 'sabutan', label: 'Sabutan' },
    { value: 'san_miguel_i', label: 'San Miguel I' },
    { value: 'san_miguel_ii', label: 'San Miguel II' },
    { value: 'san_vicente_i', label: 'San Vicente I' },
    { value: 'san_vicente_ii', label: 'San Vicente II' },
    { value: 'santol', label: 'Santol' },
    { value: 'tartaria', label: 'Tartaria' },
    { value: 'tibig', label: 'Tibig' },
    { value: 'toledo', label: 'Toledo' },
    { value: 'tubuan_i', label: 'Tubuan I' },
    { value: 'tubuan_ii', label: 'Tubuan II' },
    { value: 'tubuan_iii', label: 'Tubuan III' },
    { value: 'ulat', label: 'Ulat' },
    { value: 'yakal', label: 'Yakal' }
  ],
  gen_mariano_alvarez: [
    { value: 'aldiano_olaes', label: 'Aldiano Olaes' },
    { value: 'barangay_1_poblacion', label: 'Barangay 1 Poblacion' },
    { value: 'barangay_2_poblacion', label: 'Barangay 2 Poblacion' },
    { value: 'barangay_3_poblacion', label: 'Barangay 3 Poblacion' },
    { value: 'barangay_4_poblacion', label: 'Barangay 4 Poblacion' },
    { value: 'barangay_5_poblacion', label: 'Barangay 5 Poblacion' },
    { value: 'benjamin_tirona', label: 'Benjamin Tirona' },
    { value: 'bernardo_pulido', label: 'Bernardo Pulido' },
    { value: 'epifanio_malia', label: 'Epifanio Malia' },
    { value: 'fiorello_calimag', label: 'Fiorello Calimag' },
    { value: 'francisco_de_castro', label: 'Francisco de Castro' },
    { value: 'francisco_reyes', label: 'Francisco Reyes' },
    { value: 'gavino_maderan', label: 'Gavino Maderan' },
    { value: 'gregoria_de_jesus', label: 'Gregoria de Jesus' },
    { value: 'inocencio_salud', label: 'Inocencio Salud' },
    { value: 'jacinto_lumbreras', label: 'Jacinto Lumbreras' },
    { value: 'kapitan_kua', label: 'Kapitan Kua' },
    { value: 'koronel_jose_p_elises', label: 'Koronel Jose P. Elises' },
    { value: 'macario_dacon', label: 'Macario Dacon' },
    { value: 'marcelino_memije', label: 'Marcelino Memije' },
    { value: 'nicolasa_virata', label: 'Nicolasa Virata' },
    { value: 'pantaleon_granados', label: 'Pantaleon Granados' },
    { value: 'ramon_cruz', label: 'Ramon Cruz' },
    { value: 'san_gabriel', label: 'San Gabriel' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'severino_de_las_alas', label: 'Severino de Las Alas' },
    { value: 'tiniente_tiago', label: 'Tiniente Tiago' }
  ],
  naic: [
    { value: 'bagong_kalsada', label: 'Bagong Kalsada' },
    { value: 'balsahan', label: 'Balsahan' },
    { value: 'bancaan', label: 'Bancaan' },
    { value: 'bucana_malaki', label: 'Bucana Malaki' },
    { value: 'bucana_sasahan', label: 'Bucana Sasahan' },
    { value: 'calubcob', label: 'Calubcob' },
    { value: 'capt_c_nazareno', label: 'Capt. C. Nazareno (Poblacion)' },
    { value: 'gombalza', label: 'Gombalza (Poblacion)' },
    { value: 'halang', label: 'Halang' },
    { value: 'humbac', label: 'Humbac' },
    { value: 'ibayo_estacion', label: 'Ibayo Estacion' },
    { value: 'ibayo_silangan', label: 'Ibayo Silangan' },
    { value: 'kanluran_rizal', label: 'Kanluran Rizal' },
    { value: 'latoria', label: 'Latoria' },
    { value: 'labac', label: 'Labac' },
    { value: 'mabolo', label: 'Mabolo' },
    { value: 'malainen_bago', label: 'Malainen Bago' },
    { value: 'malainen_luma', label: 'Malainen Luma' },
    { value: 'makina', label: 'Makina' },
    { value: 'molino', label: 'Molino' },
    { value: 'munting_mapino', label: 'Munting Mapino' },
    { value: 'muzon', label: 'Muzon' },
    { value: 'palangue_2_3', label: 'Palangue 2 & 3' },
    { value: 'palangue_central', label: 'Palangue Central' },
    { value: 'sabang', label: 'Sabang' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santulan', label: 'Santulan' },
    { value: 'sapa', label: 'Sapa' },
    { value: 'timalan_balsahan', label: 'Timalan Balsahan' },
    { value: 'timalan_concepcion', label: 'Timalan Concepcion' }
  ],
  ternate: [
    { value: 'bucana', label: 'Bucana' },
    { value: 'poblacion_i', label: 'Poblacion I (Barangay I)' },
    { value: 'poblacion_i_a', label: 'Poblacion I A' },
    { value: 'poblacion_ii', label: 'Poblacion II (Barangay II)' },
    { value: 'poblacion_iii', label: 'Poblacion III (Barangay III)' },
    { value: 'san_jose', label: 'San Jose' },
    { value: 'san_juan_i', label: 'San Juan I' },
    { value: 'san_juan_ii', label: 'San Juan II' },
    { value: 'sapang_i', label: 'Sapang I' },
    { value: 'sapang_ii', label: 'Sapang II' }
  ],
  alfonso: [
    { value: 'amuyong', label: 'Amuyong' },
    { value: 'barangay_i', label: 'Barangay I (Poblacion)' },
    { value: 'barangay_ii', label: 'Barangay II (Poblacion)' },
    { value: 'barangay_iii', label: 'Barangay III (Poblacion)' },
    { value: 'barangay_iv', label: 'Barangay IV (Poblacion)' },
    { value: 'barangay_v', label: 'Barangay V (Poblacion)' },
    { value: 'bilog', label: 'Bilog' },
    { value: 'buck_estate', label: 'Buck Estate' },
    { value: 'esperanza_ibaba', label: 'Esperanza Ibaba' },
    { value: 'esperanza_ilaya', label: 'Esperanza Ilaya' },
    { value: 'kaysuyo', label: 'Kaysuyo' },
    { value: 'kaytitinga_i', label: 'Kaytitinga I' },
    { value: 'kaytitinga_ii', label: 'Kaytitinga II' },
    { value: 'kaytitinga_iii', label: 'Kaytitinga III' },
    { value: 'luksuhin', label: 'Luksuhin' },
    { value: 'luksuhin_ilaya', label: 'Luksuhin Ilaya' },
    { value: 'mangas_i', label: 'Mangas I' },
    { value: 'mangas_ii', label: 'Mangas II' },
    { value: 'marahan_i', label: 'Marahan I' },
    { value: 'marahan_ii', label: 'Marahan II' },
    { value: 'matagbak_i', label: 'Matagbak I' },
    { value: 'matagbak_ii', label: 'Matagbak II' },
    { value: 'pajo', label: 'Pajo' },
    { value: 'palumlum', label: 'Palumlum' },
    { value: 'santa_teresa', label: 'Santa Teresa' },
    { value: 'sikat', label: 'Sikat' },
    { value: 'sinaliw_malaki', label: 'Sinaliw Malaki' },
    { value: 'sinaliw_na_munti', label: 'Sinaliw na Munti' },
    { value: 'sulsugin', label: 'Sulsugin' },
    { value: 'taywanak_ibaba', label: 'Taywanak Ibaba' },
    { value: 'taywanak_ilaya', label: 'Taywanak Ilaya' },
    { value: 'upli', label: 'Upli' }
  ],
  amadeo: [
    { value: 'barangay_banay', label: 'Barangay Banay' },
    { value: 'barangay_i_pob', label: 'Barangay I (Pob.)' },
    { value: 'barangay_ii_pob', label: 'Barangay II (Pob.)' },
    { value: 'barangay_iii_pob', label: 'Barangay III (Pob.)' },
    { value: 'barangay_iv_pob', label: 'Barangay IV (Pob.)' },
    { value: 'barangay_v_pob', label: 'Barangay V (Pob.)' },
    { value: 'barangay_vi_pob', label: 'Barangay VI (Pob.)' },
    { value: 'barangay_vii_pob', label: 'Barangay VII (Pob.)' },
    { value: 'barangay_viii_pob', label: 'Barangay VIII (Pob.)' },
    { value: 'barangay_ix_pob', label: 'Barangay IX (Pob.)' },
    { value: 'barangay_x_pob', label: 'Barangay X (Pob.)' },
    { value: 'barangay_xi_pob', label: 'Barangay XI (Pob.)' },
    { value: 'barangay_xii_pob', label: 'Barangay XII (Pob.)' },
    { value: 'bucal', label: 'Bucal' },
    { value: 'buho', label: 'Buho' },
    { value: 'dagatan', label: 'Dagatan' },
    { value: 'halang', label: 'Halang' },
    { value: 'loma', label: 'Loma' },
    { value: 'maitim_i', label: 'Maitim I' },
    { value: 'maymangga', label: 'Maymangga' },
    { value: 'minantok_kanluran', label: 'Minantok Kanluran' },
    { value: 'minantok_silangan', label: 'Minantok Silangan' },
    { value: 'pangil', label: 'Pangil' },
    { value: 'salaban', label: 'Salaban' },
    { value: 'talon', label: 'Talon' },
    { value: 'tamacan', label: 'Tamacan' }
  ],
  mendez: [
    { value: 'anuling_cerca_i', label: 'Anuling Cerca I' },
    { value: 'anuling_cerca_ii', label: 'Anuling Cerca II' },
    { value: 'anuling_lejos_i', label: 'Anuling Lejos I' },
    { value: 'anuling_lejos_ii', label: 'Anuling Lejos II' },
    { value: 'asis_i', label: 'Asis I' },
    { value: 'asis_ii', label: 'Asis II' },
    { value: 'asis_iii', label: 'Asis III' },
    { value: 'banayad', label: 'Banayad' },
    { value: 'bucal', label: 'Bucal' },
    { value: 'bukal', label: 'Bukal' },
    { value: 'galicia_i', label: 'Galicia I' },
    { value: 'galicia_ii', label: 'Galicia II' },
    { value: 'galicia_iii', label: 'Galicia III' },
    { value: 'iguel_mojica', label: 'Iguël Mojica' },
    { value: 'miguel_mojica', label: 'Miguel Mojica' },
    { value: 'palocpoc_i', label: 'Palocpoc I' },
    { value: 'palocpoc_ii', label: 'Palocpoc II' },
    { value: 'panungyan_i', label: 'Panungyan I' },
    { value: 'panungyan_ii', label: 'Panungyan II' },
    { value: 'poblacion_i', label: 'Poblacion I' },
    { value: 'poblacion_ii', label: 'Poblacion II' },
    { value: 'poblacion_iii', label: 'Poblacion III' },
    { value: 'poblacion_iv', label: 'Poblacion IV' },
    { value: 'poblacion_v', label: 'Poblacion V' },
    { value: 'poblacion_vi', label: 'Poblacion VI' },
    { value: 'poblacion_vii', label: 'Poblacion VII' }
  ],
  indang: [
    { value: 'barangay_1', label: 'Barangay 1' },
    { value: 'barangay_2', label: 'Barangay 2' },
    { value: 'barangay_3', label: 'Barangay 3' },
    { value: 'barangay_4', label: 'Barangay 4' },
    { value: 'barangay_5', label: 'Barangay 5' },
    { value: 'barangay_6', label: 'Barangay 6' },
    { value: 'barangay_7', label: 'Barangay 7' },
    { value: 'barangay_8', label: 'Barangay 8' },
    { value: 'barangay_9', label: 'Barangay 9' },
    { value: 'barangay_10', label: 'Barangay 10' },
    { value: 'barangay_11', label: 'Barangay 11' },
    { value: 'barangay_12', label: 'Barangay 12' },
    { value: 'barangay_13', label: 'Barangay 13' },
    { value: 'barangay_14', label: 'Barangay 14' },
    { value: 'barangay_15', label: 'Barangay 15' },
    { value: 'barangay_16', label: 'Barangay 16' },
    { value: 'barangay_17', label: 'Barangay 17' },
    { value: 'barangay_18', label: 'Barangay 18' },
    { value: 'barangay_19', label: 'Barangay 19' },
    { value: 'barangay_20', label: 'Barangay 20' },
    { value: 'barangay_21', label: 'Barangay 21' },
    { value: 'barangay_22', label: 'Barangay 22' },
    { value: 'barangay_23', label: 'Barangay 23' }
  ]
};

// Helper function to get cities by province
export const getCitiesByProvince = (provinceValue) => {
  return CITIES_BY_PROVINCE[provinceValue] || [];
};

// Helper function to get barangays by city
export const getBarangaysByCity = (cityValue) => {
  return BARANGAYS_BY_CITY[cityValue] || BARANGAYS_BY_CITY['generic'] || [];
};

// Default country for Philippines
export const DEFAULT_COUNTRY = 'PH';

// Address labels for display
export const ADDRESS_LABELS = {
  street: 'Street Address',
  barangay: 'Barangay',
  city: 'City/Municipality',
  province: 'Province',
  zipCode: 'ZIP Code',
  country: 'Country'
};
