import React, { useEffect, useState } from 'react';
import { Activity, CheckCircle2, Package, Star, Truck, Wallet } from 'lucide-react';
import { staffService } from '../../services/apiService';
import { formatPeso } from '../../utils/paymentSummary';

const RiderDashboard = () => {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { staffService.getMyRiderDetails().then(response => setData(response.data)).catch(requestError => setError(requestError.response?.data?.message || 'Unable to load rider information.')); }, []);
  if (error) return <div className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-700">{error}</div>;
  if (!data) return <div className="flex min-h-[50vh] items-center justify-center"><Activity className="h-6 w-6 animate-spin text-primary-600"/></div>;
  const capacity = data.capacity;
  return <div className="mx-auto max-w-5xl space-y-5 pb-24">
    <header><p className="text-[10px] font-black uppercase tracking-widest text-primary-600">Delivery Rider</p><h1 className="text-2xl font-black text-slate-900">Welcome, {data.rider.firstName}</h1><p className="text-xs text-slate-500">{data.rider.riderProfile?.staffId} · {data.rider.store?.name} · {data.rider.riderProfile?.accountStatus}</p></header>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[[Package,'Assigned',data.stats.totalAssigned],[CheckCircle2,'Completed',data.stats.completed],[Activity,'Success rate',`${data.stats.successRate}%`],[Star,'Rating',data.stats.totalRatings?`${data.stats.averageRating} (${data.stats.totalRatings})`:'No ratings yet'],[Wallet,'Available',formatPeso(data.earnings.available)]].map(([Icon,label,value])=><div key={label} className="rounded-xl border bg-white p-4"><Icon className="mb-2 h-4 w-4 text-primary-600"/><p className="text-[9px] font-black uppercase text-slate-400">{label}</p><p className="text-lg font-black text-slate-900">{value}</p></div>)}</div>
    <section className="rounded-xl border bg-white p-4" aria-label="Vehicle capacity summary"><div className="mb-3 flex items-center gap-2"><Truck className="h-4 w-4 text-primary-600"/><h2 className="text-xs font-black uppercase tracking-widest">Vehicle & Capacity</h2></div>{capacity?.configured?<dl className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-4"><div><dt className="text-slate-400">Vehicle</dt><dd className="mt-1 font-black capitalize">{capacity.vehicleType?.replaceAll('_',' ')}</dd></div><div><dt className="text-slate-400">Maximum</dt><dd className="mt-1 font-black">{capacity.maxWeightKg} kg · {capacity.maxParcelCount} parcel(s)</dd></div><div><dt className="text-slate-400">Reserved</dt><dd className="mt-1 font-black">{capacity.reservedWeightKg} kg · {capacity.reservedParcelCount} parcel(s)</dd></div><div><dt className="text-slate-400">Remaining</dt><dd className="mt-1 font-black text-emerald-700">{capacity.remainingWeightKg} kg · {capacity.remainingParcelCount} parcel(s)</dd></div></dl>:<div className="rounded-lg bg-amber-50 p-3 text-xs font-bold text-amber-800">Vehicle setup required. Contact your Store administrator before accepting new automatic assignments.</div>}</section>
    <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="text-xs font-black uppercase tracking-widest">Assigned Deliveries</h2><p className="mt-1 text-[10px] text-slate-400">Assignments are available only through your authenticated rider account.</p></div>{data.deliveries.length?data.deliveries.map(delivery=>{const address=delivery.order?.shippingAddress;return <div key={delivery._id} className="flex items-center justify-between gap-3 border-b p-4 text-xs last:border-0"><div className="min-w-0"><p className="font-black text-slate-800">{delivery.order?.orderNumber||`DLV-${String(delivery._id).slice(-8).toUpperCase()}`}</p><p className="text-slate-500">{delivery.order?.customer?.firstName} {delivery.order?.customer?.lastName}</p>{address&&<p className="truncate text-[10px] text-slate-400">{[address.street,address.barangay,address.city].filter(Boolean).join(', ')}</p>}<p className="mt-1 text-[9px] text-slate-400">{delivery.parcel?.weightKg?`${delivery.parcel.weightKg} kg · ${delivery.parcel.parcelCount} parcel(s) · `:''}Assigned {delivery.assignedAt?new Date(delivery.assignedAt).toLocaleString():'recently'}</p></div><div className="shrink-0 text-right"><p className="text-[10px] font-black uppercase">{delivery.status?.replace(/_/g,' ')}</p>{delivery.isLive&&<a href={`/rider/deliveries/${delivery._id}`} className="mt-2 inline-flex rounded-lg bg-slate-900 px-3 py-2 text-[9px] font-black uppercase text-white">Open delivery</a>}</div></div>}):<p className="p-6 text-center text-xs text-slate-400">No assigned deliveries yet.</p>}</section>
    <section className="rounded-xl border bg-white p-4"><h2 className="mb-3 text-xs font-black uppercase tracking-widest">My earnings and payouts</h2><div className="grid grid-cols-3 gap-2 text-center"><div><p className="text-[9px] text-slate-400">Today</p><b className="text-sm">{formatPeso(data.earnings.today)}</b></div><div><p className="text-[9px] text-slate-400">Pending</p><b className="text-sm">{formatPeso(data.earnings.pending)}</b></div><div><p className="text-[9px] text-slate-400">Paid</p><b className="text-sm">{formatPeso(data.earnings.totalPaid)}</b></div></div></section>
  </div>;
};

export default RiderDashboard;
