import React, { useEffect, useState } from 'react';
import { Activity, CheckCircle2, Package, Wallet } from 'lucide-react';
import { staffService } from '../../services/apiService';

const money = value => `₱${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const RiderDashboard = () => {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { staffService.getMyRiderDetails().then(response => setData(response.data)).catch(error => setError(error.response?.data?.message || 'Unable to load rider information.')); }, []);
  if (error) return <div className="p-5 bg-rose-50 border border-rose-200 rounded-xl text-sm text-rose-700">{error}</div>;
  if (!data) return <div className="min-h-[50vh] flex items-center justify-center"><Activity className="w-6 h-6 animate-spin text-primary-600"/></div>;
  return <div className="max-w-5xl mx-auto space-y-5 pb-24">
    <header><p className="text-[10px] font-black uppercase tracking-widest text-primary-600">Delivery Rider</p><h1 className="text-2xl font-black text-slate-900">Welcome, {data.rider.firstName}</h1><p className="text-xs text-slate-500">{data.rider.riderProfile?.staffId} · {data.rider.store?.name} · {data.rider.riderProfile?.accountStatus}</p></header>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[[Package,'Assigned',data.stats.totalAssigned],[CheckCircle2,'Completed',data.stats.completed],[Activity,'Success rate',`${data.stats.successRate}%`],[Wallet,'Available',money(data.earnings.available)]].map(([Icon,label,value])=><div key={label} className="bg-white border rounded-xl p-4"><Icon className="w-4 h-4 text-primary-600 mb-2"/><p className="text-[9px] font-black uppercase text-slate-400">{label}</p><p className="text-lg font-black text-slate-900">{value}</p></div>)}</div>
    <section className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b"><h2 className="text-xs font-black uppercase tracking-widest">Assigned Deliveries</h2><p className="text-[10px] text-slate-400 mt-1">Only deliveries assigned to your staff account are shown.</p></div>{data.deliveries.length ? data.deliveries.map(delivery=>{const address=delivery.order?.shippingAddress; const cod=['cod','cash_on_delivery'].includes(delivery.order?.paymentMethod); return <div key={delivery._id} className="p-4 border-b last:border-0 flex justify-between items-center gap-3 text-xs"><div className="min-w-0"><p className="font-black text-slate-800">{delivery.order?.orderNumber || delivery.trackingToken}</p><p className="text-slate-500">{delivery.order?.customer?.firstName} {delivery.order?.customer?.lastName}</p>{address&&<p className="text-[10px] text-slate-400 truncate">{[address.street,address.barangay,address.city].filter(Boolean).join(', ')}</p>}<p className="text-[9px] text-slate-400 mt-1">Assigned {delivery.assignedAt ? new Date(delivery.assignedAt).toLocaleString() : 'recently'}{cod ? ` · COD ${money(delivery.order?.totalAmount)}` : ''}</p></div><div className="text-right shrink-0"><p className="font-black uppercase text-[10px]">{delivery.status?.replace(/_/g,' ')}</p>{delivery.isLive&&<a href={`/rider-track/${delivery.riderToken}`} className="inline-flex mt-2 px-3 py-2 rounded-lg bg-slate-900 text-white text-[9px] font-black uppercase">Open delivery</a>}</div></div>}) : <p className="p-6 text-center text-xs text-slate-400">No assigned deliveries yet.</p>}</section>
    <section className="bg-white border rounded-xl p-4"><h2 className="text-xs font-black uppercase tracking-widest mb-3">My earnings and payouts</h2><div className="grid grid-cols-3 gap-2 text-center"><div><p className="text-[9px] text-slate-400">Today</p><b className="text-sm">{money(data.earnings.today)}</b></div><div><p className="text-[9px] text-slate-400">Pending</p><b className="text-sm">{money(data.earnings.pending)}</b></div><div><p className="text-[9px] text-slate-400">Paid</p><b className="text-sm">{money(data.earnings.totalPaid)}</b></div></div>{data.payouts.map(payout=><div key={payout._id} className="mt-3 pt-3 border-t flex justify-between text-xs"><span>{payout.payoutId} · {payout.status}</span><b>{money(payout.amount)}</b></div>)}</section>
  </div>;
};

export default RiderDashboard;
