import React, { useEffect, useState } from 'react';
import { Calendar, CheckCircle2, Clock3, ExternalLink, FileBadge, ShieldCheck, Upload, X } from 'lucide-react';
import { toast } from 'react-toastify';
import { getImageUrl, staffService } from '../../services/apiService';

const roleLabel = value => String(value || '').replace(/_/g, ' ').replace(/\b\w/g, character => character.toUpperCase());
const list = value => (value || []).map(item => item?.name || item).filter(Boolean).join(', ') || 'Not provided';
const chipStyle = status => ({ verified: 'bg-emerald-50 text-emerald-700', expired: 'bg-rose-50 text-rose-700', suspended: 'bg-rose-50 text-rose-700', archived: 'bg-slate-100 text-slate-500' }[status] || 'bg-amber-50 text-amber-700');

export default function SpecializedStaffProfileModal({ data, onClose }) {
  const [details, setDetails] = useState(data);
  const [submitting, setSubmitting] = useState(false);
  const [credential, setCredential] = useState({ documentType: 'professional_license', name: '', issuingBody: '', credentialNumber: '', expiresAt: '', file: null, replacesDocumentId: '' });
  useEffect(() => setDetails(data), [data]);
  useEffect(() => {
    const close = event => { if (event.key === 'Escape' && !submitting) onClose(); };
    window.addEventListener('keydown', close);
    return () => window.removeEventListener('keydown', close);
  }, [onClose, submitting]);
  if (!details) return null;
  const { staff, activity = {}, performance = {}, recentReviews = [], activityTimeline = [] } = details;
  const profile = staff.professionalProfile || {};
  const documents = profile.credentialDocuments || [];
  const isSpecialized = staff.staffStatus !== 'archived' && ['veterinarian','veterinary_technician','veterinary_assistant','groomer','trainer','boarding_staff','boarding_specialist'].includes(staff.staffType || staff.role);

  const reload = async () => {
    const response = await staffService.getProfile(staff._id);
    setDetails(response.data);
  };
  const uploadCredential = async event => {
    event.preventDefault();
    if (!credential.file || !credential.name.trim()) return toast.error('Credential name and document are required.');
    const formData = new FormData();
    Object.entries(credential).forEach(([key, value]) => value && key !== 'file' && formData.append(key, value));
    formData.append('document', credential.file);
    setSubmitting(true);
    try {
      await staffService.uploadCredential(staff._id, formData);
      toast.success(credential.replacesDocumentId ? 'Credential renewed; previous version archived.' : 'Credential uploaded for verification.');
      setCredential({ documentType: 'professional_license', name: '', issuingBody: '', credentialNumber: '', expiresAt: '', file: null, replacesDocumentId: '' });
      await reload();
    } catch (error) { toast.error(error.response?.data?.message || 'Unable to upload credential.'); }
    finally { setSubmitting(false); }
  };
  const setVerification = async (documentId, status) => {
    if (!window.confirm(`Mark this credential ${status.replaceAll('_', ' ')}?`)) return;
    try {
      await staffService.updateCredentialVerification(staff._id, documentId, { status });
      toast.success('Verification status updated.');
      await reload();
    } catch (error) { toast.error(error.response?.data?.message || 'Unable to update verification.'); }
  };

  return <div className="fixed inset-0 z-[60] bg-black/50 p-3 flex items-center justify-center"><div className="bg-white rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto shadow-2xl">
    <header className="sticky top-0 bg-white border-b p-4 flex justify-between gap-3 z-10"><div className="flex items-center gap-3">{staff.avatar?<img src={getImageUrl(staff.avatar)} alt="" className="w-11 h-11 rounded-xl object-cover border"/>:<div className="w-11 h-11 rounded-xl bg-slate-100 flex items-center justify-center text-xs font-black">{staff.firstName?.[0]}{staff.lastName?.[0]}</div>}<div><div className="flex items-center gap-2"><p className="text-[9px] uppercase tracking-widest font-black text-emerald-600">Staff Profile</p>{staff.professionalVerificationStatus==='verified'&&<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-0.5 text-[8px] font-black uppercase text-emerald-700"><ShieldCheck size={10}/>Verified</span>}</div><h2 className="text-lg font-black">{staff.firstName} {staff.lastName}</h2><p className="text-[10px] text-slate-500">{profile.staffId} · {roleLabel(staff.staffType)} · {staff.store?.name} · {staff.staffStatus || (staff.isActive?'active':'inactive')}</p></div></div><button onClick={onClose} className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center"><X size={14}/></button></header>
    <div className="p-4 space-y-5">
      <section className="grid sm:grid-cols-2 gap-3 text-xs">{[['Professional title',profile.professionalTitle],['Specialty / area',profile.specialty],['Experience',`${profile.experienceYears || 0} years`],['Qualifications',list(profile.qualifications)],['Certifications',list(profile.certifications)],['Training',list(profile.training)],['Areas of expertise',list(profile.areasOfExpertise)],['Languages',list(profile.languages)],['Registration information',profile.registration?.number ? `${profile.registration.type || 'Registration'}: ${profile.registration.number}${profile.registration.issuingBody ? ` · ${profile.registration.issuingBody}` : ''}` : 'Not provided']].map(([label,value])=><div key={label} className="border rounded-xl p-3"><p className="text-[8px] uppercase font-black text-slate-400 mb-1">{label}</p><p className="font-bold text-slate-700">{value || 'Not provided'}</p></div>)}</section>
      {profile.bio&&<section className="rounded-xl border p-3"><p className="text-[8px] uppercase font-black text-slate-400 mb-1">Professional biography</p><p className="text-xs leading-relaxed text-slate-600">{profile.bio}</p></section>}

      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Performance Overview</h3><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">{[['Completed',performance.completedServices],['Rating',performance.reviewCount?`${performance.averageRating}/5`:'—'],['Reviews',performance.reviewCount],['Upcoming',performance.upcomingBookings],['Active',performance.activeServices],['Cancellation',`${performance.cancellationRate||0}%`],['Success',`${performance.successRate||0}%`]].map(([label,value])=><div key={label} className="border rounded-xl p-2.5 bg-slate-50"><p className="text-[8px] uppercase font-black text-slate-400">{label}</p><p className="text-sm font-black text-slate-800 mt-1">{value ?? 0}</p></div>)}</div></section>

      {isSpecialized&&<section><div className="flex items-center justify-between gap-2 mb-2"><h3 className="text-[10px] uppercase tracking-widest font-black">Credential Verification</h3><span className={`rounded-full px-2 py-1 text-[8px] font-black uppercase ${chipStyle(profile.verification?.status)}`}>{(profile.verification?.status||'pending_verification').replaceAll('_',' ')}</span></div>
        <div className="space-y-2">{documents.length?documents.map(document=><article key={document._id} className={`rounded-xl border p-3 ${document.status==='archived'?'opacity-60 bg-slate-50':'bg-white'}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex items-center gap-2"><FileBadge size={14} className="text-primary-600"/><p className="text-xs font-black text-slate-800">{document.name}</p><span className={`rounded-full px-2 py-0.5 text-[8px] font-black uppercase ${chipStyle(document.status)}`}>{document.status?.replaceAll('_',' ')}</span></div><p className="mt-1 text-[10px] text-slate-500">{[roleLabel(document.documentType),document.issuingBody,document.credentialNumber,document.expiresAt?`Expires ${new Date(document.expiresAt).toLocaleDateString()}`:'No expiry'].filter(Boolean).join(' · ')}</p><p className="text-[9px] text-slate-400">Uploaded {document.uploadedAt?new Date(document.uploadedAt).toLocaleDateString():'—'}{document.verifiedAt?` · Verified ${new Date(document.verifiedAt).toLocaleDateString()}`:''}</p></div><div className="flex flex-wrap gap-1"><a href={document.documentUrl} target="_blank" rel="noreferrer" className="h-8 px-2 rounded-lg border inline-flex items-center gap-1 text-[9px] font-black uppercase"><ExternalLink size={11}/>Internal file</a>{document.status!=='archived'&&<><button onClick={()=>setCredential(current=>({...current,documentType:document.documentType,name:document.name,issuingBody:document.issuingBody||'',credentialNumber:document.credentialNumber||'',replacesDocumentId:document._id}))} className="h-8 px-2 rounded-lg border text-[9px] font-black uppercase">Renew</button><button onClick={()=>setVerification(document._id,'verified')} className="h-8 px-2 rounded-lg bg-emerald-600 text-white text-[9px] font-black uppercase">Verify</button><button onClick={()=>setVerification(document._id,'expired')} className="h-8 px-2 rounded-lg border text-rose-600 text-[9px] font-black uppercase">Expire</button><button onClick={()=>setVerification(document._id,'suspended')} className="h-8 px-2 rounded-lg border text-rose-600 text-[9px] font-black uppercase">Suspend</button></>}</div></div></article>):<p className="rounded-xl border bg-slate-50 p-3 text-xs text-slate-500">No credential documents uploaded. Customers cannot see this internal area.</p>}</div>
        <form onSubmit={uploadCredential} className="mt-3 rounded-xl border bg-slate-50 p-3"><div className="flex items-center gap-2 mb-2"><Upload size={13}/><p className="text-[9px] font-black uppercase">{credential.replacesDocumentId?'Renew Credential':'Upload Credential'}</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2"><select value={credential.documentType} onChange={event=>setCredential(current=>({...current,documentType:event.target.value}))} className="h-9 px-2 rounded-lg border bg-white text-xs"><option value="professional_license">Professional License</option><option value="certification">Certification</option><option value="training_certificate">Training Certificate</option></select><input value={credential.name} onChange={event=>setCredential(current=>({...current,name:event.target.value}))} className="h-9 px-2 rounded-lg border text-xs" placeholder="Credential name"/><input value={credential.issuingBody} onChange={event=>setCredential(current=>({...current,issuingBody:event.target.value}))} className="h-9 px-2 rounded-lg border text-xs" placeholder="Issuing body"/><input value={credential.credentialNumber} onChange={event=>setCredential(current=>({...current,credentialNumber:event.target.value}))} className="h-9 px-2 rounded-lg border text-xs" placeholder="License / credential number"/><input type="date" value={credential.expiresAt} onChange={event=>setCredential(current=>({...current,expiresAt:event.target.value}))} className="h-9 px-2 rounded-lg border text-xs"/><input type="file" accept=".pdf,.doc,.docx,image/*" onChange={event=>setCredential(current=>({...current,file:event.target.files?.[0]||null}))} className="h-9 px-2 py-1.5 rounded-lg border bg-white text-[10px]"/></div><div className="mt-2 flex justify-end gap-2">{credential.replacesDocumentId&&<button type="button" onClick={()=>setCredential({ documentType:'professional_license',name:'',issuingBody:'',credentialNumber:'',expiresAt:'',file:null,replacesDocumentId:'' })} className="h-8 px-3 rounded-lg border text-[9px] font-black uppercase">Cancel renewal</button>}<button disabled={submitting} className="h-8 px-3 rounded-lg bg-primary-600 text-white text-[9px] font-black uppercase disabled:opacity-50">{submitting?'Uploading…':'Save Document'}</button></div></form>
      </section>}

      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Assigned Services</h3><div className="grid sm:grid-cols-2 gap-2">{staff.assignedServices?.length?staff.assignedServices.map(service=><div key={service._id} className="border rounded-xl p-3 flex justify-between gap-2 text-xs"><b>{service.name}</b><span className="text-[9px] text-slate-400 uppercase">{service.category?.replace(/_/g,' ')}</span></div>):<p className="text-xs text-slate-400">No services assigned.</p>}</div></section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Availability</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{Object.entries(profile.availability || {}).map(([day,value])=><div key={day} className={`rounded-xl p-2 border text-[10px] ${value?.available?'bg-emerald-50 text-emerald-700':'bg-slate-50 text-slate-400'}`}><b className="capitalize">{day}</b><p>{value?.available?`${value.start}–${value.end}`:'Unavailable'}</p>{value?.breaks?.length>0&&<p className="text-[8px]">Break {value.breaks.map(item=>`${item.start}–${item.end}`).join(', ')}</p>}</div>)}</div>{profile.leaveSchedule?.length>0&&<div className="mt-2 text-[10px] text-slate-600">Leave: {profile.leaveSchedule.map(item=>`${new Date(item.startDate).toLocaleDateString()}–${new Date(item.endDate).toLocaleDateString()}`).join(', ')}</div>}{(profile.temporaryUnavailable?.active||profile.emergencyUnavailable?.active)&&<p className="mt-2 rounded-lg bg-rose-50 p-2 text-[10px] font-bold text-rose-700">Currently unavailable: {profile.emergencyUnavailable?.active?'Emergency status':`until ${profile.temporaryUnavailable?.until?new Date(profile.temporaryUnavailable.until).toLocaleString():'further notice'}`}</p>}</section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Service Activity</h3><div className="grid grid-cols-3 gap-2 mb-3">{[[Calendar,'Upcoming',activity.upcoming?.length],[CheckCircle2,'Completed',activity.completed],[Clock3,'Cancelled / no-show',activity.cancelled]].map(([Icon,label,value])=><div key={label} className="border rounded-xl p-3"><Icon size={13} className="text-emerald-600"/><p className="text-[8px] uppercase text-slate-400 mt-2">{label}</p><b>{value || 0}</b></div>)}</div><div className="border rounded-xl divide-y">{activity.upcoming?.length?activity.upcoming.map(booking=><div key={booking._id} className="p-3 flex justify-between gap-3 text-[10px]"><div><b>{booking.service?.name}</b><p className="text-slate-400">Pet: {booking.pet?.name}</p></div><div className="text-right"><b>{new Date(booking.bookingDate).toLocaleDateString()}</b><p className="text-slate-400">{booking.startTime}–{booking.endTime}</p></div></div>):<p className="p-4 text-center text-xs text-slate-400">No upcoming bookings.</p>}</div></section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Booking Timeline</h3><div className="relative ml-2 border-l border-slate-200 pl-4">{(activity.history||[]).slice(0,8).map(booking=><article key={booking._id} className="relative pb-3 last:pb-0"><span className="absolute -left-[19px] top-1 h-2 w-2 rounded-full bg-primary ring-2 ring-white"/><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black text-slate-800">{booking.service?.name||'Service booking'}</p><p className="text-[9px] text-slate-500">{booking.pet?.name||'Pet'} · {roleLabel(booking.status)}</p></div><time className="shrink-0 text-[9px] text-slate-400">{new Date(booking.bookingDate||booking.createdAt).toLocaleDateString()}</time></div></article>)}{!(activity.history||[]).length&&<p className="pb-2 text-xs text-slate-400">No booking history yet.</p>}</div></section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Effective Permission Preview</h3><div className="flex flex-wrap gap-1.5">{(staff.effectivePermissions||[]).length?(staff.effectivePermissions||[]).map(permission=><span key={permission} className="rounded-lg bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">{roleLabel(permission.replace('.', ' · '))}</span>):<p className="text-xs text-slate-400">No operational permissions are assigned to this role.</p>}</div><p className="mt-2 text-[9px] text-slate-400">Read only · inherited from the {roleLabel(staff.effectiveRole||staff.staffType)} role policy.</p></section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Staff Activity Timeline</h3><div className="border rounded-xl divide-y">{activityTimeline.length?activityTimeline.map(item=><div key={item._id} className="p-3 flex items-start justify-between gap-3"><div><p className="text-[10px] font-black text-slate-800">{item.action}</p><p className="text-[10px] text-slate-500">{item.details}</p></div><time className="shrink-0 text-[9px] text-slate-400">{new Date(item.createdAt).toLocaleString()}</time></div>):<p className="p-4 text-center text-xs text-slate-400">No recorded staff activity yet.</p>}</div></section>
      {recentReviews.length>0&&<section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Recent Customer Reviews</h3><div className="grid sm:grid-cols-2 gap-2">{recentReviews.map(review=><article key={review._id} className="rounded-xl border bg-slate-50 p-3"><div className="flex justify-between text-[10px] font-black"><span>{review.user?`${review.user.firstName} ${review.user.lastName}`:'Anonymous customer'}</span><span className="text-amber-600">{review.rating}/5</span></div>{review.comment&&<p className="text-xs text-slate-600 mt-1">{review.comment}</p>}</article>)}</div></section>}
    </div>
  </div></div>;
}
