import React from 'react';
import { Calendar, CheckCircle2, Clock3, X } from 'lucide-react';
import { getImageUrl } from '../../services/apiService';

const roleLabel = value => String(value || '').replace(/_/g,' ').replace(/\b\w/g, character => character.toUpperCase());
const list = value => (value || []).map(item => item?.name || item).filter(Boolean).join(', ') || 'Not provided';

export default function SpecializedStaffProfileModal({ data, onClose }) {
  if (!data) return null;
  const { staff, activity } = data;
  const profile = staff.professionalProfile || {};
  return <div className="fixed inset-0 z-[60] bg-black/50 p-3 flex items-center justify-center"><div className="bg-white rounded-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto shadow-2xl">
    <header className="sticky top-0 bg-white border-b p-4 flex justify-between gap-3 z-10"><div className="flex items-center gap-3">{staff.avatar?<img src={getImageUrl(staff.avatar)} alt="" className="w-11 h-11 rounded-xl object-cover border"/>:<div className="w-11 h-11 rounded-xl bg-slate-100 flex items-center justify-center text-xs font-black">{staff.firstName?.[0]}{staff.lastName?.[0]}</div>}<div><p className="text-[9px] uppercase tracking-widest font-black text-emerald-600">Specialized Staff Profile</p><h2 className="text-lg font-black">{staff.firstName} {staff.lastName}</h2><p className="text-[10px] text-slate-500">{profile.staffId} · {roleLabel(staff.staffType)} · {staff.store?.name} · {staff.staffStatus || (staff.isActive?'active':'inactive')}</p></div></div><button onClick={onClose} className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center"><X size={14}/></button></header>
    <div className="p-4 space-y-4">
      <section className="grid sm:grid-cols-2 gap-3 text-xs">{[['Professional title',profile.professionalTitle],['Specialty / area',profile.specialty],['Experience',`${profile.experienceYears || 0} years`],['Qualifications',list(profile.qualifications)],['Certifications',list(profile.certifications)],['Training',list(profile.training)],['Areas of expertise',list(profile.areasOfExpertise)],['Registration information',profile.registration?.number ? `${profile.registration.type || 'Registration'}: ${profile.registration.number}${profile.registration.issuingBody ? ` · ${profile.registration.issuingBody}` : ''}` : 'Not provided']].map(([label,value])=><div key={label} className="border rounded-xl p-3"><p className="text-[8px] uppercase font-black text-slate-400 mb-1">{label}</p><p className="font-bold text-slate-700">{value || 'Not provided'}</p></div>)}</section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Assigned Services</h3><div className="grid sm:grid-cols-2 gap-2">{staff.assignedServices?.length?staff.assignedServices.map(service=><div key={service._id} className="border rounded-xl p-3 flex justify-between gap-2 text-xs"><b>{service.name}</b><span className="text-[9px] text-slate-400 uppercase">{service.category?.replace(/_/g,' ')}</span></div>):<p className="text-xs text-slate-400">No services assigned.</p>}</div></section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Availability</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{Object.entries(profile.availability || {}).map(([day,value])=><div key={day} className={`rounded-xl p-2 border text-[10px] ${value?.available?'bg-emerald-50 text-emerald-700':'bg-slate-50 text-slate-400'}`}><b className="capitalize">{day}</b><p>{value?.available?`${value.start}–${value.end}`:'Unavailable'}</p></div>)}</div></section>
      <section><h3 className="text-[10px] uppercase tracking-widest font-black mb-2">Service Activity</h3><div className="grid grid-cols-3 gap-2 mb-3">{[[Calendar,'Upcoming',activity.upcoming?.length],[CheckCircle2,'Completed',activity.completed],[Clock3,'Cancelled / no-show',activity.cancelled]].map(([Icon,label,value])=><div key={label} className="border rounded-xl p-3"><Icon size={13} className="text-emerald-600"/><p className="text-[8px] uppercase text-slate-400 mt-2">{label}</p><b>{value || 0}</b></div>)}</div><div className="border rounded-xl divide-y">{activity.upcoming?.length?activity.upcoming.map(booking=><div key={booking._id} className="p-3 flex justify-between gap-3 text-[10px]"><div><b>{booking.service?.name}</b><p className="text-slate-400">Pet: {booking.pet?.name}</p></div><div className="text-right"><b>{new Date(booking.bookingDate).toLocaleDateString()}</b><p className="text-slate-400">{booking.startTime}–{booking.endTime}</p></div></div>):<p className="p-4 text-center text-xs text-slate-400">No upcoming bookings.</p>}</div></section>
    </div>
  </div></div>;
}
